### ISSUE TITLE
feral wolves attack other tamed mobs

### ISSUE THREAD

**Issue by RealisticMC73309** [itsmeow/betteranimalsplus#260] opened 2021-07-28 15:12 UTC
**Describe the bug**
if you accidently hit a tamed mob your tamed feral wolves will go after it

**To Reproduce**
1. Spawn and tame a feral wolf
2. spawn and tame another tameable entity
3. punch the tameable entity and see the error

**Log output/error (if present)**
Get your minecraft log and paste it here.
[latest.log](https://github.com/itsmeow/betteranimalsplus/files/6894151/latest.log)

**Expected behavior**
feral wolves, when tamed shouldn't attack your other pets

**Screenshots**
![2021-07-28_09 05 24](https://user-images.githubusercontent.com/38083040/127347482-0f300de3-3317-4763-80ba-21bbf47a55b3.png)

**Versions:**
 - Minecraft Version: 1.16.5
 - Forge Version: 36.1.31
 - Mod Version: 10.2.0

**Additional context**

**Comment by itsmeow** [comment] 2021-12-10 00:24
Closing as duplicate of #250 (merging issues)

**Closed as completed by itsmeow** 2021-12-10 00:24 UTC
Labels: bug, mc:1.16
