### ISSUE TITLE
Crash in the render

### ISSUE THREAD

**Issue by Veijar** [itsmeow/betteranimalsplus#175] opened 2020-06-05 00:18 UTC
The Game crashin the render with some times when any mobs appears.

---- Minecraft Crash Report ----
// My bad.

Time: 4/06/20 07:12 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at its_meow.betteranimalsplus.client.renderer.entity.RenderWhale.render(RenderWhale.java:37) ~[?:8.2.1.96] {re:classloading}
	at its_meow.betteranimalsplus.client.renderer.entity.RenderWhale.func_225623_a_(RenderWhale.java:14) ~[?:8.2.1.96] {re:classloading}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:300) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:add-render,xf:OptiFine:default}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1855) ~[?:?] {re:classloading,xf:OptiFine:default,xf:fml:sereneseasons:temperature_transformer}
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:385) ~[?:?] {re:classloading}
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4248) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:926) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:686) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:924) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.74.jar:31.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$425/501491806.call(Unknown Source) [forge-1.15.2-31.1.74.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at its_meow.betteranimalsplus.client.renderer.entity.RenderWhale.render(RenderWhale.java:37)
	at its_meow.betteranimalsplus.client.renderer.entity.RenderWhale.func_225623_a_(RenderWhale.java:14)

-- Entity being rendered --
Details:
	Entity Type: betteranimalsplus:whale (its_meow.betteranimalsplus.common.entity.EntityWhale)
	Entity ID: 32680
	Entity Name: Whale
	Entity's Exact location: 1466.50, 57.00, -184.50
	Entity's Block location: World: (1466,57,-185), Chunk: (at 10,3,7 in 91,-12; contains blocks 1456,0,-192 to 1471,255,-177), Region: (2,-1; contains chunks 64,-32 to 95,-1, blocks 1024,0,-512 to 1535,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: its_meow.betteranimalsplus.client.renderer.entity.RenderWhale@1d58892c
	Location: -507.05,-26.72,101.42 - World: (-508,-27,101), Chunk: (at 4,-2,5 in -32,6; contains blocks -512,0,96 to -497,255,111), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Rotation: 106.875
	Delta: 0.70002246
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:300)
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1855)
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:385)
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4248)
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:926)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['MrBargz'/31472, l='MpServer', x=1533.70, y=65.00, z=-230.62]]
	Chunk stats: Client Chunk Cache: 729, 481
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: -5942481998956150258
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (16,66,-48), Chunk: (at 0,4,0 in 1,-3; contains blocks 16,0,-48 to 31,255,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 6248480 game time, 147774 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:611)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1763)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:567)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$425/501491806.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4200966712 bytes (4006 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.1.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.74.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.74.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.74.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.74.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.15.2_HD_U_G1_pre19.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.1.74.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.74
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		Ma-Enchants-1.15.2-3.1.0.jar Ma Enchants {ma-enchants@1.15.2-3.1.0 DONE}
		animalnet-v1.15.2+Forge+b1.jar AnimalNet {animalnet@v1.15.2 Forge b1 DONE}
		mining-helmet-1.15.2-1.0.6.jar Mining Helmet {mining_helmet@1.0.6 DONE}
		xray-1.15.2-2.2.0.jar Advanced XRay {xray@2.2.0 DONE}
		bambooblocks-1.15.2-1.3.jar Bamboo Blocks {bambooblocks@1.2.11 DONE}
		vilnames_1.15-2.0.jar Villager Names {vilnames@2.0 DONE}
		jei-1.15.2-6.0.0.4.jar Just Enough Items {jei@6.0.0.4 DONE}
		buzzierbees-1.4.jar Buzzier Bees {buzzierbees@1.4 DONE}
		mcw-windows-1.0.1-mc1.15.2_1.15.1.jar Macaw's Windows {mcwwindows@1.0.1 DONE}
		Upgrade-Aquatic-1.15.2-v1.5.1.jar Upgrade Aquatic {upgrade_aquatic@1.5.1 DONE}
		SneakyMagic-v2.0-1.15.2.jar Sneaky Magic {sneakymagic@2.0 DONE}
		bloomful-1.15.2-1.3.2.jar Bloomful {bloomful@NONE DONE}
		invtweaks-1.15.2-1.0.1.jar Inventory Tweaks Reborn {invtweaks@1.15.2-1.0.1 DONE}
		extraboats-1.3.5-1.15.2.jar Extra Boats {extraboats@1.3.5 DONE}
		Neat+1.6-22.jar Neat {neat@1.6-22 DONE}
		ForgeEndertech-1.15.2-6.0.2.2-build.0030.jar Forge Endertech {forgeendertech@6.0.2.2 DONE}
		XaerosWorldMap_1.6.2_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.6.2 DONE}
		RingOfRepair-1.15.2-1.1.27.jar Ring of Repair {ring_of_repair@1.1.27 DONE}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 DONE}
		comforts-FORGE-1.15.2-2.0.0.2.jar Comforts {comforts@FORGE-1.15.2-2.0.0.2 DONE}
		NaturesCompass-1.15.2-1.8.4.jar Nature's Compass {naturescompass@1.15.2-1.8.4 DONE}
		SereneSeasons-1.15.2-3.0.0.69-universal.jar Serene Seasons {sereneseasons@1.15.2-3.0.0.69 DONE}
		decorative_blocks-6d.jar Decorative Blocks {decorative_blocks@1.6 DONE}
		AdHooks-1.15.2-5.0.0.0-build.0004.jar Advanced Hook Launchers {adhooks@5.0.0.0 DONE}
		betteranimalsplus-1.15.2-8.2.1.96.jar Better Animals Plus {betteranimalsplus@8.2.1.96 DONE}
		branders-enhanced-spawnermod-1.15.2-1.6.4.jar Enhanced Mob Spawners {spawnermod@1.6.4 DONE}
		Bookshelf-1.15.2-5.5.33.jar Bookshelf {bookshelf@5.5.33 DONE}
		BotanyPots-1.15.2-2.0.14.jar BotanyPots {botanypots@2.0.14 DONE}
		u_team_core-1.15.2-2.11.0.156.jar U Team Core {uteamcore@2.11.0.156 DONE}
		Aquatic+Armors-1.1.jar Aquatic Armors {aquaticarmors@1.1 DONE}
		mcw-doors-1.0.0-mc1.15.2.jar Macaw's Doors {mcwdoors@1.0.0 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		CraftTweaker-1.15.2-6.0.0.24.jar CraftTweaker {crafttweaker@6.0.0.24 DONE}
		swampexpansion-1.15.2-1.6.1.jar Swamp Expansion {swampexpansion@NONE DONE}
		forge-1.15.2-31.1.74-universal.jar Forge {forge@31.1.74 DONE}
		MinersAdvantage-1.15.2-1.6.7.29.jar MinersAdvantage {minersadvantage@1.15.2-1.6.7.29 DONE}
		forge-1.15.2-31.1.74-client.jar Minecraft {minecraft@1.15.2 DONE}
		mcw-bridges-1.0.3-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.3 DONE}
		useful_backpacks-1.15.2-1.9.4.63.jar Useful Backpacks {usefulbackpacks@1.9.4.63 DONE}
		AmbientSounds_v3.0.19_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		BiomesOPlenty-1.15.2-10.0.0.345-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.342 DONE}
		phosphor-forge-mc1.15.2-0.5.2+build.4.jar Phosphor {phosphor@0.5.2+build.4 DONE}
		Blur-1.1.0-1.jar Blur {blur@1.1.0-1 DONE}
		StructureCompass-1.15-1.2.jar Structure Compass Mod {structurecompass@1.2 DONE}
		AdLods-1.15.2-3.0.3.0-build.0035.jar Large Ore Deposits {adlods@3.0.3.0 DONE}
		simplefarming-1.15.2-1.2.9.jar Simple Farming {simplefarming@1.15.2-1.2.9 DONE}
		astikorcarts-1.0.2-1.15.2.jar AstikorCarts {astikorcarts@1.0.2 DONE}
		Xaeros_Minimap_20.12.2_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.12.2 DONE}
		autumnity-1.2.0-1.15.2.jar Autumnity {autumnity@1.2.0 DONE}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 DONE}
		Quark-r2.1-235.jar Quark {quark@r2.1-235 DONE}
		OreExcavation-1.7.151.jar Ore Excavation {oreexcavation@NONE DONE}
		simplytea-1.15.2-2.2.0.jar Simply Tea {simplytea@1.15.2-2.2.0 DONE}
		obfuscate-0.4.3-1.15.2.jar Obfuscate {obfuscate@0.4.3 DONE}
		vehicle-mod-0.44.0-1.15.2.jar MrCrayfish's Vehicle Mod {vehicle@0.44.0 DONE}
		AttainedDrops-1.15.2-6.0.7.jar Attained Drops {attained_drops@6.0.7 DONE}
		mcw-roofs-1.0.2-mc1.15.2_1.15.1.jar Macaw's Roofs {mcwroofs@1.0.2 DONE}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		globalxp-1.15.2-v1.4.11.jar Global XP {globalxp@v1.4.11 DONE}
		incubation-1.0.4-1.15.2.jar Incubation {incubation@1.0.4 DONE}
		SuperTools-1.1_1.15.2.jar Super Tools {supertools@1.1 DONE}
	Launched Version: 1.15.2-forge-31.1.74
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060/PCIe/SSE2 GL version 4.6.0 NVIDIA 446.14, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Español (México)
	CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre19
	OptiFine Build: 20200601-002451
	Render Distance Chunks: 15
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.27 Extreme.zip
	OpenGlVersion: 4.6.0 NVIDIA 446.14
	OpenGlRenderer: GeForce GTX 1060/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by itsmeow** [comment] 2020-06-05 02:04
Duplicate of #165 (for reasons other than same crash, thank you for your report!)

**Closed as completed by itsmeow** 2020-06-05 02:04 UTC
