### ISSUE TITLE
Goose creating entity ticking error

### ISSUE THREAD

**Issue by N1KAMI** [itsmeow/betteranimalsplus#314] opened 2022-03-06 22:12 UTC
## Describe what you were doing before the crash

Walking around, adjusting keybinds to test Origins mods

## To Reproduce

Steps to reproduce the behavior (if possible):
1. Spawn in
2. Walk around for any amount of time
3. See error

## Crash Log (REQUIRED)

[crash-2022-03-06_14.01.55-server.txt](https://github.com/itsmeow/betteranimalsplus/files/8193623/crash-2022-03-06_14.01.55-server.txt)

## Versions
- Minecraft Version: 1.18.1
- Architectury API Version: 1.18.1
- Platform (Forge/Fabric): Fabric
- Forge Version: v.0.193.2.1
- Fabric Loader Version: 0.13.3
- Fabric API Version: 1.18.1
- Mod Version: 1.18.1

## Additional context
crash occurred directly after pressing "\" key which is the lightning summon toggle for origins,  but has occurred multiple other times without an apparent trigger

**Comment by itsmeow** [comment] 2022-03-07 16:53
Duplicate of #306, upgrade to collective 4.9

**Closed as completed by itsmeow** 2022-03-07 16:53 UTC
