### ISSUE TITLE
[1.14.4] Server hard lock - its_meow.betteranimalsplus.common.entity.EntityPheasant.onLivingUpdate()100.00%24100ms

### ISSUE THREAD

**Issue by ProsperCraft** [itsmeow/betteranimalsplus#122] opened 2019-12-13 21:41 UTC
Server hard locked for two hours, I ran a warmroast and got this-
its_meow.betteranimalsplus.common.entity.EntityPheasant.onLivingUpdate()100.00%24100ms

![d33819c099dd49d71901acf1d3883fcf](https://user-images.githubusercontent.com/4427684/70834064-92a8a280-1db6-11ea-9bc6-29b0b5fc011a.png)

**Versions:**
 - Forge Version: forge-1.14.4-28.1.104
 - MC Version:1.14.4
 - Mod Version:betteranimalsplus-1.14.4-8.0.0

**Comment by itsmeow** [comment] 2019-12-13 23:50
Hmmm... There is not much I can do to diagnose this issue since this seems to be just passing through the living update method, rather than executing the remaining code (any of my code)... something else is happening here.

**Comment by LemADEC** [comment] 2019-12-28 01:56
thread is parked, means another thread is holding a lock, warmroast screenshot is only covering the main server thread. Maybe the server logs includes a dump of all threads?

**Comment by itsmeow** [comment] 2019-12-28 02:00
@LemADEC is correct

**Comment by itsmeow** [comment] 2020-01-04 20:19
Closing until someone can reproduce with an all-thread dump

**Closed by itsmeow** 2020-01-04 20:19 UTC
Labels: bug, mc:1.14, priority:low, problems reproducing, side:server
