### ISSUE TITLE
Lamprey Bug

### ISSUE THREAD

**Issue by ent1119** [itsmeow/betteranimalsplus#345] opened 2022-06-08 17:13 UTC
## Describe the bug
Dead lamprey animation keeps spawning on player when passing over a certain area

## To Reproduce
1. seed: (might be helpful) -9011734522541469937. world edited (water lake rarity:90 lava, lake rarity: 96, Iron ore common: spawn size 21, spawn tries 22, max height 75
2. cave near spawn, 
3. random place in that cave does that weird glitch.
4. See error.

## Expected behavior
while in random part of cave; lamprey dead animation (while clinged to body) starts. (happens every time i walk over the area)
Beaware; character was bitten by a lamprey before the glitch

## Screenshots
-Could not capture screen shots since bug ceased after rejoining-

## Versions
 - Minecraft Version: 1.12.2 
 - Architectury API Version: NiL
 - Platform (Forge/Fabric): Forge
 - Forge Version: 1.12.2
 - Fabric Loader Version: NiL
 - Fabric API Version: NiL
 - Mod Version: 1.12.2

## Additional context
started survival world, got bitten by lamprey, made a base in a cave, the glitch happens.
after rejoining the glitch ceased but it's still a bug so might as well report that.

**Comment by itsmeow** [comment] 2022-06-08 19:41
Duplicate of #305

**Closed as not planned** 2022-12-21 04:11 UTC
