### ISSUE TITLE
Crash when teleporting due to `Invalid entity data item type` on a feral wolf

### ISSUE THREAD

**Issue by netcore10** [itsmeow/betteranimalsplus#338] opened 2022-05-24 00:07 UTC
## Describe the bug
An entity caused a client crash. mentions feral wolf
## To Reproduce

not sure to be honest

## Log output/error (if present)
[latest.log](https://github.com/itsmeow/betteranimalsplus/files/8758625/latest.log)

## Versions
 - Minecraft Version: 1.18.2
 - Architectury API Version: 4.4.61
 - Platform (Forge/Fabric): fabric
 - Fabric Loader Version: 0.14.5
 - Fabric API Version: 0.53
 - Mod Version: 11.0.5

## Additional context
I was on a server, but only my client crashed

**Comment by itsmeow** [comment] 2022-05-24 03:54
Duplicate of #294 (same underlying cause)

**Closed as completed by itsmeow** 2022-05-24 03:54 UTC
