### ISSUE TITLE
Error related to Shark rendering 

### ISSUE THREAD

**Issue by Fertigware** [itsmeow/betteranimalsplus#173] opened 2020-05-29 21:32 UTC
**Describe what you were doing before the crash**
It seems a bit random, had crashes while in caves, on mainland or near water. 
Crashes on Mac aswell Windows Clients.

**Crash Log (REQUIRED)**
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 29.05.20 23:19
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at its_meow.betteranimalsplus.client.renderer.entity.RenderShark.render(RenderShark.java:36) ~[?:8.2.1.96] {re:classloading}
	at its_meow.betteranimalsplus.client.renderer.entity.RenderShark.func_225623_a_(RenderShark.java:14) ~[?:8.2.1.96] {re:classloading}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:245) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:add-render,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1094) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:948) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:600) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:422) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:924) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) ~[1.15.2-forge-31.2.5.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.15.2-31.2.5.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at its_meow.betteranimalsplus.client.renderer.entity.RenderShark.render(RenderShark.java:36)
	at its_meow.betteranimalsplus.client.renderer.entity.RenderShark.func_225623_a_(RenderShark.java:14)

-- Entity being rendered --
Details:
	Entity Type: betteranimalsplus:shark (its_meow.betteranimalsplus.common.entity.EntityShark)
	Entity ID: 19194
	Entity Name: Shark
	Entity's Exact location: -135.50, 51.00, 96.50
	Entity's Block location: World: (-136,51,96), Chunk: (at 8,3,0 in -9,6; contains blocks -144,0,96 to -129,255,111), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: its_meow.betteranimalsplus.client.renderer.entity.RenderShark@37f91e0a
	Location: -82.66,-12.27,-65.15 - World: (-83,-13,-66), Chunk: (at 13,-1,14 in -6,-5; contains blocks -96,0,-80 to -81,255,-65), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Rotation: 4.21875
	Delta: 0.72001046
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:245)
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1094)
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:948)
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:600)

-- Affected level --
Details:
	All players: 3 total; [ClientPlayerEntity['Fertigware'/11269, l='MpServer', x=-52.84, y=62.00, z=161.65], RemoteClientPlayerEntity['RaZZoReD'/2683, l='MpServer', x=-104.91, y=20.00, z=94.76], RemoteClientPlayerEntity['misssorceress'/8603, l='MpServer', x=-53.49, y=62.00, z=161.24]]
	Chunk stats: Client Chunk Cache: 729, 502
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: -2605837669382872157
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-176,63,61), Chunk: (at 0,3,13 in -11,3; contains blocks -176,0,48 to -161,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 82459 game time, 67776 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:442)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1763)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:567)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Mac OS X (x86_64) version 10.15.4
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3619082256 bytes (3451 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 12
	JVM Flags: 8 total; -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.5.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.5.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.5.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.5.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.2.5.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.5
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		forge-1.15.2-31.2.5-client.jar Minecraft {minecraft@1.15.2 DONE}
		useful_backpacks-1.15.2-1.9.4.63.jar Useful Backpacks {usefulbackpacks@1.9.4.63 DONE}
		SilentLib-1.15.2-4.6.1+49.jar Silent Lib {silentlib@4.6.1+49 DONE}
		BiomesOPlenty-1.15.2-10.0.0.363-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.363 DONE}
		MekanismAdditions-1.15.2-9.10.7.420.jar Mekanism: Additions {mekanismadditions@9.10.7 DONE}
		berry_good-2.0.0.jar Berry Good {berry_good@2.0 DONE}
		BetterThanBunnies-1.15.2-1.2.0.jar Better Than Bunnies {betterthanbunnies@1.2.0 DONE}
		SilentGear-1.15.2-1.6.4+90.jar Silent Gear {silentgear@1.6.4+90 DONE}
		jei-1.15.2-6.0.0.4.jar Just Enough Items {jei@6.0.0.4 DONE}
		simplefarming-1.15.2-1.2.9.jar Simple Farming {simplefarming@1.15.2-1.2.9 DONE}
		Abnormals-Core-1.15.2-v1.0.4.jar Abnormals Core {abnormals_core@1.0.4 DONE}
		Buzzier-Bees-1.15.2-v1.5.0.jar Buzzier Bees {buzzierbees@v1.5.0 DONE}
		Atmospheric-1.15.2-v1.3.0.jar Atmospheric {atmospheric@v1.3.0 DONE}
		planttech2-0.02.10+-+1.15.2.jar PlantTech 2 {planttech2@0.02.10 DONE}
		Mekanism-1.15.2-9.10.7.420.jar Mekanism {mekanism@9.10.7 DONE}
		Upgrade-Aquatic-1.15.2-v1.6.1.jar Upgrade Aquatic {upgrade_aquatic@1.6.1 DONE}
		Bloomful-1.15.2-v1.4.0.jar Bloomful {bloomful@NONE DONE}
		Savage-and-Ravage-1.15.2-v1.1.2.jar Savage & Ravage {savageandravage@v1.1.2 DONE}
		Mantle-1.15.2-1.5.15.jar Mantle {mantle@1.5.15 DONE}
		BetterCaves-1.15.2-1.0.jar YUNG's Better Caves {bettercaves@1.15.2-1.0 DONE}
		gravestone-1.17.5.jar Gravestone Mod {gravestone@1.17.5 DONE}
		Clumps-5.0.2.jar Clumps {clumps@5.0.2 DONE}
		FastWorkbench-1.15.1-3.0.0.jar FastWorkbench {fastbench@3.0.0 DONE}
		CookingForBlockheads_1.15.2-8.0.2.jar Cooking for Blockheads {cookingforblockheads@8.0.2 DONE}
		autumnity-1.3.1-1.15.2.jar Autumnity {autumnity@1.3.1 DONE}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 DONE}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 DONE}
		Animalium-0.5.3.jar Animalium {animalium@0.5.3 DONE}
		betteranimalsplus-1.15.2-8.2.1.96.jar Better Animals Plus {betteranimalsplus@8.2.1.96 DONE}
		Bookshelf-1.15.2-5.6.38.jar Bookshelf {bookshelf@5.6.38 DONE}
		EnchantmentDescriptions-1.15.2-2.0.8.jar EnchantmentDescriptions {enchdesc@2.0.8 DONE}
		The-Endergetic-Expansion-1.15.2-v1.3.1.jar The Endergetic Expansion {endergetic@1.3.1 DONE}
		u_team_core-1.15.2-2.11.0.156.jar U Team Core {uteamcore@2.11.0.156 DONE}
		MekanismTools-1.15.2-9.10.7.420.jar Mekanism: Tools {mekanismtools@9.10.7 DONE}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 DONE}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		deathquotes-1.15.1-1.0.jar DeathQuotes {deathquotes@1.15.1-1.0 DONE}
		MekanismGenerators-1.15.2-9.10.7.420.jar Mekanism: Generators {mekanismgenerators@9.10.7 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		TMechworks-1.15.2-2.1.0.jar Tinkers' Mechworks {tmechworks@2.1.0 DONE}
		XL-Food-Mod-1.15.2-2.2.2.jar XL Food Mod {xlfoodmod@2.2.2 DONE}
		Swamp-Expansion-1.15.2-v1.7.1.jar Swamp Expansion {swampexpansion@NONE DONE}
		forge-1.15.2-31.2.5-universal.jar Forge {forge@31.2.5 DONE}
		Quark-r2.1-238.jar Quark {quark@r2.1-238 DONE}
		ruins-1.15.1.3.jar Ruins {ruins@1.15.1.3 DONE}
		FastLeafDecay-v22.jar FastLeafDecay {fastleafdecay@v22 DONE}
	Launched Version: 1.15.2-forge-31.2.5
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: AMD Radeon Pro 5300M OpenGL Engine GL version 2.1 ATI-3.8.24, ATI Technologies Inc.
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz

**Versions:**
 - OS: Windows 10 aswell as MacOS Catalina (10.15.4 - latest)
 - MC Version: 1.15.2
 - Mod Version: 8.2.1 BETA 96 (newest on curse forge)

**Additional context**
Before creating this report, me and my buddy crashed at the same time while being near each other.

**Comment by itsmeow** [comment] 2020-05-29 21:49
Duplicate of #165

**Closed as completed by itsmeow** 2020-05-29 21:49 UTC

**Comment by itsmeow** [comment] 2020-06-04 09:33
Just to note myself, this isn't a duplicate because the crash is the same, the CAUSE is the same, in that entities do not have proper "default" variants if the data returned is null, or, if they do, methods/fields are attempted to be used on null.
