### ISSUE TITLE
Certain Mobs not working well with vanilla in SMP 1.15.2

### ISSUE THREAD

**Issue by Arteowo** [itsmeow/betteranimalsplus#180] opened 2020-06-18 00:34 UTC
We've had an issue of whenever Reindeer (and so far only reindeer) go through the nether portal they crash our server, as well as feeding Vanilla foxes Pheasant crashes the server, and I feel if we tested more we could probably find a few things that'll continue to crash it.

As for reproducing I think what I said above is sufficient, it could be also conflicting mods within the mod pack created for my friends and I, we just wanted to share this issue incase it was something wrong with the mod itself, as for mods we include

Biomes O plenty
Pam's crops, trees and food
Waddles
MrCrayfish's furniture.
Terraforged.

Hope any issues get resolved!

[crash-2020-06-17_19.40.54-server.txt](https://github.com/itsmeow/betteranimalsplus/files/4795644/crash-2020-06-17_19.40.54-server.txt
[crash-2020-06-17_00.35.09-server.txt](https://github.com/itsmeow/betteranimalsplus/files/4795645/crash-2020-06-17_00.35.09-server.txt)
)

**Versions:**
 - OS: Windows
 - MC Version: 1.15.2
 - Mod Version: The very latest for 1.15.2

**Comment by itsmeow** [comment] 2020-06-18 00:38
First log is a duplicate of #174 
Second log has no determinable cause,
None of these logs contain any sort of vanilla foxes and pheasants, or reindeer.

**Comment by itsmeow** [comment] 2020-06-18 00:38
Also is "very latest" the latest alpha or the one on CurseForge? There are multiple "latest"s

**Comment by Arteowo** [comment] 2020-06-18 00:46
Latest on curseforge sorry, and as for the pheasant we tested it 3 times and each time it was the same outcome, I can try and give you both crash reports of the outcome.

**Comment by Arteowo** [comment] 2020-06-18 00:49
Oh my bad, just got confirmation from my players that it was a coyote getting fed pheasant meat.
[crash-2020-06-17_19.37.28-server.txt](https://github.com/itsmeow/betteranimalsplus/files/4795693/crash-2020-06-17_19.37.28-server.txt)
[crash-2020-06-17_19.35.16-server.txt](https://github.com/itsmeow/betteranimalsplus/files/4795694/crash-2020-06-17_19.35.16-server.txt)
[crash-2020-06-17_19.40.54-server (3).txt](https://github.com/itsmeow/betteranimalsplus/files/4795695/crash-2020-06-17_19.40.54-server.3.txt)

Sorry for the misunderstanding!

**Comment by Arteowo** [comment] 2020-06-18 00:53
And as for the nether logs I don't think they would show much but I'll give you those too
[crash-2020-06-17_00.26.33-server.txt](https://github.com/itsmeow/betteranimalsplus/files/4795703/crash-2020-06-17_00.26.33-server.txt)
[crash-2020-06-17_00.34.09-server.txt](https://github.com/itsmeow/betteranimalsplus/files/4795704/crash-2020-06-17_00.34.09-server.txt)

These should be the right files, sorry for any confusion again!

**Comment by itsmeow** [comment] 2020-06-19 01:26
Aha! The reindeer crash is another symptom of #165! Closing as duplicate.

**Closed as completed by itsmeow** 2020-06-19 01:26 UTC
