### ISSUE TITLE
Massive Tarantula overspawn 1.15.2

### ISSUE THREAD

**Issue by ZigTheHedge** [itsmeow/betteranimalsplus#181] opened 2020-06-18 10:04 UTC
**Describe the bug**
Default server config. Tarantulas spawn in the air and fall on the ground (sometimes even die on impact), resulting in a massive amount of them.

**To Reproduce**
Install Biosheres mod (https://www.curseforge.com/minecraft/mc-mods/biospheres-mod) and find the biome good for Tarantulas (minecraft:badlands in my case) or just create a void world with a suitable biome (spheres or void world to increase spawn chances). Enjoy watching falling Tarantulas :) 

**Log output/error (if present)**
Nope

**Expected behavior**
They shouldn't be this much.

**Screenshots**
https://imgur.com/EkbZxaN

**Versions:**
 - OS: Win10
 - MC Version: 1.15.2
 - Mod Version: 8.2.1.96

**Comment by itsmeow** [comment] 2020-06-19 01:30
Try lowering the spawnrates in the server configuration (see FAQ) and get back to me.

**Comment by itsmeow** [comment] 2020-06-19 01:31
It is quite weird that they would spawn in the air, considering vanilla mobs don't. Perhaps this is caused by the generator mods registering their own spawns differently?

**Comment by itsmeow** [comment] 2020-07-31 02:06
Closing as weird edge case. Probably biosphere's fault

**Closed as completed by itsmeow** 2020-07-31 02:06 UTC
Labels: bug, question, mod compat, problems reproducing, mc:1.15
