### ISSUE TITLE
[1.15.2] Crashing randomly

### ISSUE THREAD

**Issue by spmino** [itsmeow/betteranimalsplus#195] opened 2020-08-11 07:08 UTC
Was just walking around near a river. Using 1.15.2 with betteranimalsplus-1.15.2-8.2.1.118.jar. Using HR New Beginnings modpack.

**Crash Log (REQUIRED)**
https://paste.ee/p/p51dB - Crash Log
https://paste.ee/p/xzg9o - Crash Report

**Versions:**
 - Minecraft Version: 1.15.2
 - Forge Version: 31.2.30
 - Mod Version: 1.15.2-8.2.1.118.jar

**Comment by itsmeow** [comment] 2020-08-11 17:32
Duplicate of #194

**Closed as completed** 2020-08-11 17:32 UTC
