### ISSUE TITLE
Zotzypres + Skeleton = Not good

### ISSUE THREAD

**Issue by grayscale420** [itsmeow/betteranimalsplus#134] opened 2020-01-17 00:59 UTC
If being succed by a Zotzypres and a skeleton shoots you (or possibly the bat) the game crashes.

[latest.log](https://github.com/itsmeow/betteranimalsplus/files/4074472/latest.log)

**Crash Log (REQUIRED)**
(https://github.com/itsmeow/betteranimalsplus/files/4074475/crash-2020-01-16_11.47.38-client.txt)

**Versions:**
 - Forge Version: 28.1.114
 - MC Version: 1.14.4
 - Mod Version: 8.1.0

**Comment by itsmeow** [comment] 2020-01-17 20:04
Ah, so it seems this is a duplicate of #131 that you encountered the proper way to reproduce! Either way, it's fixed in development and will come out in the next release :D

**Closed by itsmeow** 2020-01-17 20:04 UTC
Labels: crash, mc:1.14, priority:medium, problems reproducing
