### ISSUE TITLE
Crashed upon loading world.

### ISSUE THREAD

**Issue by bloodconfetti** [itsmeow/betteranimalsplus#82] opened 2019-08-09 04:09 UTC
[crash-2019-08-08_22.04.15-server.txt](https://github.com/itsmeow/betteranimalsplus/files/3484695/crash-2019-08-08_22.04.15-server.txt)
**Describe what you were doing before the crash**
Loading game

**To Reproduce** (Required unless unknown)
Steps to reproduce the behavior (if possible):
1. Pull up MC launcher, push play, select 'Single Player', select World, see error: The game crashed whilst ticking memory connection
Error: java.lang.IllegalArgumentException: Invalid message its_meow.betteranimalsplus.network.ClientConfigurationPacket

**Crash Log (REQUIRED)**
Uploaded above.

**Versions:**
 - Forge Version: 28.0.45
 - MC Version: 1.14.4
 - Mod Version: betteranimalsplus-1.14.4-7.0.2.1

**Comment by itsmeow** [comment] 2019-08-09 04:15
It seems as though the packet system is not registered for some reason, which implies there was an issue constructing the mod in the first place. Can I get a full debug.log from the logs folder?

**Comment by bloodconfetti** [comment] 2019-08-09 04:40
[debug-4.log.gz](https://github.com/itsmeow/betteranimalsplus/files/3484769/debug-4.log.gz)
[debug-5.log.gz](https://github.com/itsmeow/betteranimalsplus/files/3484770/debug-5.log.gz)
[debug.log](https://github.com/itsmeow/betteranimalsplus/files/3484771/debug.log)
[debug-1.log.gz](https://github.com/itsmeow/betteranimalsplus/files/3484772/debug-1.log.gz)
[debug-2.log.gz](https://github.com/itsmeow/betteranimalsplus/files/3484773/debug-2.log.gz)
[debug-3.log.gz](https://github.com/itsmeow/betteranimalsplus/files/3484774/debug-3.log.gz)

sorry, I'm not sure which one you needed...

**Comment by itsmeow** [comment] 2019-08-09 04:43
That's... huh. It looks like you have the wrong Forge version / mod version match.. but you don't. Maybe I made a mistake. I'll look at this more later. The actuall error is a ClassNotFound for the events that were moved in 28.0.45.

**Comment by itsmeow** [comment] 2019-08-10 21:50
This issue is caused by another mod that is not up to date for Forge 28.0.45. I think it's corail_pillar. Closing.

**Closed by itsmeow** 2019-08-10 21:50 UTC
Labels: crash, mc:1.14, priority:medium

**Comment by Corail31** [comment] 2019-08-11 03:02
hey meow, mod doesn't need to update to 45... they need to update if they use specific events of fml package...

**Comment by itsmeow** [comment] 2019-08-11 03:26
That was only my guess, but it must be something else in your pack, mine is up to date as well. No bad intentions @Corail31

**Comment by bloodconfetti** [comment] 2019-08-11 06:12
Oh no I didn't mean it like that. I just thought maybe they saw something in the coding that lead them to believe that... Absolutely didn't mean to create conflict.
