### ISSUE TITLE
With the default 1.12.2 config, hostile mobs rarely spawn

### ISSUE THREAD

**Issue by joe-p** [itsmeow/betteranimalsplus#170] opened 2020-05-14 18:11 UTC
**Environment**
Server: forge-1.12.2-14.23.5.2854

Modlist:
- AutoRegLib-1.3-32.jar
- betteranimalsplus-1.12.2-9.0.1.jar
- bettercaves-1.12.2-2.0.2.jar
- BetterDiving-1.12.2-1.5.3.jar
- Chameleon-1.12-4.1.3.jar
- furniture-6.3.1-1.12.2.jar
- gravestone-1.10.3.jar
- Mantle-1.12-1.3.3.55.jar
- movingelevators-1.2.16-mc1.12.jar
- Quark-r1.6-179.jar
- StorageDrawers-1.12.2-5.4.2.jar
- TConstruct-1.12.2-2.13.0.183.jar
- TinkerToolLeveling-1.12.2-1.1.0.jar
- Traverse-1.12.2-1.6.0-69.jar

**Initial Problem**
With the default config I was barely seeing any hostile mobs spawn. This was most notable in caves, where there were effectively zero mobs spawning (about one encountered every 30 minutes or so). The server was on survival (normal), so obviously something wasn't right.

**Solution**
I did a search and replace in the config file, replacing every "allowDespawning=false" with "allowDespawning=true". After restarting the server the mobs were spawning in the caves at a normal (much higher than before) rate. 

**Narrowing Down on The Bug**
I don't have time to narrow down on the bug right now, but I assume it's one of the hostile mobs increasing the mob limit and not letting other hostile mobs spawn. If needed I can spend more time with just BaP installed and try to see which mob is the culprit.

**Comment by itsmeow** [comment] 2020-05-14 21:38
Another symptom of a broken spawning system... Thanks Minecraft. I honestly have no clue why this would happen, it's like those damned eels. Minecraft has some of the wonkiest spawning ever. I understand more and more why DrZhark made CMS. Except CMS doesn't work.

**Comment by joe-p** [comment] 2020-05-15 15:01
Yeah, I did see #167 but have yet to confirm if the eels are the culprit on my server. If it is the eels taking up the hostile mob limit, McJty's [In Control!](https://www.curseforge.com/minecraft/mc-mods/in-control) _might_ be a temporary band-aid solution to those encountering the same problem.

**Comment by itsmeow** [comment] 2020-05-15 21:11
Yeah, but eels aren't classified as hostile mobs (spawning wise). The only things that are MONSTER spawn type are zotzpyre and tarantula.

**Comment by itsmeow** [comment] 2020-05-15 21:12
Also, hostile mobs ignore the limit, which is what is confusing me most. Only CREATURE types are affected by the limit.

**Comment by joe-p** [comment] 2020-05-17 00:42
I mistook the lampreys for eels, which I why I initially thought they were considered hostile. 

Regardless, I realized that eels could not be the source of this bug. I fixed it by changing all of the entities that had a default allowDespawning value of false to true. The entities with false as the default are as follows:

- goat
- goose
- bear
- bearneutral
- deer
- lammergeier
- feralwolf
- fox
- hirschgeist
- pheasant
- reindeer
- boar
- squirrel
- songbird
- badger
- crab
- horseshoecrab
- moose
- turkey
- walrus
- coyote

This means that it is one of these entities that was causing the problem. Unfortunately, it's hard to narrow it down since I need to play on the server for an extended period of time to allow the culprit entity to spawn (assuming I even go in the respective biome). The only entity with a potential mod conflict is the crab, which is also spawned by Quark. Disabling the crabs from Quark, however, did not fix the problem so it's likely not a conflict issue.

**Comment by itsmeow** [comment] 2020-06-10 00:55
Yeah I'm not sure what's causing this... Having CREATURE type spawns despawn like mobs is just odd and breaks the convention of what other animals do in vanilla. More confusing, no one else has reported this issue, ever, as far as I know.

**Comment by ColaLiao** [comment] 2020-08-24 15:10
i have same issue, but in my case,
zombie will never spawn in plains biome.

i have to remove this mod to solve it😢

mod ver. 
betteranimalsplus-1.12.2-9.0.1.jar

**Comment by ColaLiao** [comment] 2020-08-24 15:31
i try to use previous ver.
Better Animals Plus 1.12.2-9.0.0
and it works well 😃

**Comment by ColaLiao** [comment] 2020-08-24 17:44
i try to use previous ver.
betteranimalsplus-1.12.2-9.0.0.jar
it work well so far.

**Comment by itsmeow** [comment] 2020-09-20 00:36
Cannot reproduce and issue is old. Closing.

**Closed as completed by itsmeow** 2020-09-20 00:36 UTC
Labels: bug, problems reproducing, priority:low, mc:1.12
