### ISSUE TITLE
1.14.4 mod isnt loading. 

### ISSUE THREAD

**Issue by PASSTHEBLEACH** [itsmeow/betteranimalsplus#132] opened 2020-01-10 05:49 UTC
When trying to run this mod with no others, I get this error. 

[modloading-worker-1/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to register automatic subscribers. ModID: betteranimalsplus, class its_meow.betteranimalsplus.BetterAnimalsPlusMod
java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent

**Comment by itsmeow** [comment] 2020-01-10 05:50
Mod version? Forge version? Full log?

**Comment by PASSTHEBLEACH** [comment] 2020-01-10 07:34
I was using the newest 1.14.4  8.1.0 version of betteranimalsplus. Kept getting that same error with any forge version above 28.1.108... 28.1.108 forge actually fixed my issue, I'm not sure what was wrong, but after playing around with it I found a good forge/mod mix I guess lol.. Sorry for wasting your time! My boyfriend and I were both having this problem, so it may happen to others, so decided to explain how I fixed. :)

**Comment by itsmeow** [comment] 2020-01-10 11:44
No no, this still could very much be an issue! We can't have new forge versions breaking the mod!

**Comment by PASSTHEBLEACH** [comment] 2020-01-11 00:18
I understand! I just played around with the forge versions and found a fix :)

**Comment by itsmeow** [comment] 2020-01-11 16:17
What confuses me is that event you're getting an error for has not been in that location since extremely early (pre 28.1.0) Forge 1.14 versions, and no mod version has used it since 7.1.1- are you sure your versions are correct? Can I get a full log dump?

**Comment by itsmeow** [comment] 2020-01-11 16:18
![image](https://user-images.githubusercontent.com/10366817/72207149-04cae080-3464-11ea-86b7-30537e687ee5.png)
Just as an example, this is what 8.1.0 is currently using, not the one referenced in your error log

**Comment by itsmeow** [comment] 2020-01-23 18:03
Assuming invalid forge version and closing. Unless more information comes up I am unable to reproduce this on the latest forge versions. Tested outside of dev environment on Forge 28.1.116 and was unable to reproduce with version 1.14.4-8.1.0

**Closed by itsmeow** 2020-01-23 18:03 UTC
Labels: crash, mc:1.14, priority:low, problems reproducing
