### ISSUE TITLE
Better Animals Plus 1.16.1 Build Crashes Consistently

### ISSUE THREAD

**Issue by Foozey** [itsmeow/betteranimalsplus#189] opened 2020-07-16 08:11 UTC
**Describe what you were doing before the crash**
Flying around the world, just generally testing the mod.

**To Reproduce**
Steps to reproduce the behavior (if possible):
1. Create a world
2. Fly around through as many biomes as possible
3. Wait for crash

**Crash Log (REQUIRED)**
`---- Minecraft Crash Report ----
// Don't do that.

Time: 16/07/20 6:00 PM
Description: Exception generating new chunk

java.lang.NullPointerException: Exception generating new chunk
	at net.minecraft.nbt.StringNBT.func_229705_a_(StringNBT.java:40) ~[?:?] {re:classloading}
	at net.minecraft.nbt.CompoundNBT.func_74778_a(CompoundNBT.java:150) ~[?:?] {re:classloading}
	at dev.itsmeow.betteranimalsplus.imdlib.entity.util.IVariantTypes.writeType(IVariantTypes.java:41) ~[?:9.0.1] {re:classloading}
	at its_meow.betteranimalsplus.common.entity.util.abstracts.EntityAnimalWithTypes.func_184198_c(EntityAnimalWithTypes.java:30) ~[?:9.0.1] {re:classloading}
	at net.minecraft.entity.Entity.func_70039_c(Entity.java:1332) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkPrimer.func_76612_a(ChunkPrimer.java:216) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.WorldGenRegion.func_217376_c(WorldGenRegion.java:252) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_77191_a(WorldEntitySpawner.java:370) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.NoiseChunkGenerator.func_230354_a_(NoiseChunkGenerator.java:614) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$12(ChunkStatus.java:89) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$2196/990826507.doWork(Unknown Source) ~[?:?] {}
	at net.minecraft.world.chunk.ChunkStatus$ISelectiveWorker.doWork(ChunkStatus.java:240) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:691) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.world.server.ChunkManager$$Lambda$5175/216863107.apply(Unknown Source) ~[?:?] {}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-3.0.25.jar:?] {}
	at net.minecraft.world.server.ChunkManager.lambda$chunkGenerate$20(ChunkManager.java:689) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.world.server.ChunkManager$$Lambda$5160/334857863.apply(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$5173/1251119799.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) ~[?:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.nbt.StringNBT.func_229705_a_(StringNBT.java:40)
	at net.minecraft.nbt.CompoundNBT.func_74778_a(CompoundNBT.java:150)
	at dev.itsmeow.betteranimalsplus.imdlib.entity.util.IVariantTypes.writeType(IVariantTypes.java:41)
	at its_meow.betteranimalsplus.common.entity.util.abstracts.EntityAnimalWithTypes.func_184198_c(EntityAnimalWithTypes.java:30)
	at net.minecraft.entity.Entity.func_70039_c(Entity.java:1332)
	at net.minecraft.world.chunk.ChunkPrimer.func_76612_a(ChunkPrimer.java:216)
	at net.minecraft.world.gen.WorldGenRegion.func_217376_c(WorldGenRegion.java:252)
	at net.minecraft.world.spawner.WorldEntitySpawner.func_77191_a(WorldEntitySpawner.java:370)
	at net.minecraft.world.gen.NoiseChunkGenerator.func_230354_a_(NoiseChunkGenerator.java:614)
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$12(ChunkStatus.java:89)
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$2196/990826507.doWork(Unknown Source)
	at net.minecraft.world.chunk.ChunkStatus$ISelectiveWorker.doWork(ChunkStatus.java:240)
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198)

-- Chunk to be generated --
Details:
	Location: 67,-56
	Position hash: -240518168509
	Generator: net.minecraft.world.gen.NoiseChunkGenerator@7ba05d94
Stacktrace:
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:691)
	at net.minecraft.world.server.ChunkManager$$Lambda$5175/216863107.apply(Unknown Source)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.world.server.ChunkManager.lambda$chunkGenerate$20(ChunkManager.java:689)
	at net.minecraft.world.server.ChunkManager$$Lambda$5160/334857863.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58)
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$5173/1251119799.run(Unknown Source)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['FUZEmc'/244, l='ServerLevel[Test]', x=872.86, y=80.30, z=-682.74]]
	Chunk stats: ServerChunkCache: 4773
	Level dimension: minecraft:overworld
	Level spawn location: World: (-1,63,-16), Chunk: (at 15,3,0 in -1,-1; contains blocks -16,0,-16 to -1,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 2488 game time, 2488 day time
	Level name: Test
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 20986 (now: false), thunder time: 13435 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:858)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:791)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:121)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643)
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230)
	at net.minecraft.server.MinecraftServer$$Lambda$4982/1561386756.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4360204816 bytes (4158 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.66.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.66.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.66.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.66.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.16.1_HD_U_G2_pre4.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.1-32.0.66.jar fml TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.66
	FML Language Providers: 
		javafml@32.0
		minecraft@1
	Mod List: 
		forge-1.16.1-32.0.66-client.jar Minecraft {minecraft@1.16.1 DONE}
		betteranimalsplus-1.16.1-9.0.1.3.jar Better Animals Plus {betteranimalsplus@9.0.1 DONE}
		forge-1.16.1-32.0.66-universal.jar Forge {forge@32.0.66 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['FUZEmc'/244, l='ServerLevel[Test]', x=872.86, y=80.30, z=-682.74]]
	Data Packs: vanilla, mod:betteranimalsplus (incompatible), mod:forge (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.16.1_HD_U_G2_pre4
	OptiFine Build: 20200711-211327
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: projectLUMA.zip
	OpenGlVersion: 4.6.0 NVIDIA 451.67
	OpenGlRenderer: GeForce GTX 1080 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8`

**Versions:**
 - Minecraft Version: 1.16.1
 - Forge Version: 1.16.1 (32.0.66)
 - Mod Version: 1.16.1 Github Build

**Additional context**
Tried with other mods originally which made me discover the crash. Then tried this mod by itself with no other mods, same crash result. If you need anything to help fix the problem, just let me know. Thanks.

**Comment by itsmeow** [comment] 2020-08-07 21:03
This crash is (probably?) fixed in 276c28957e1f68b7b11ecd0c5d14824706f52ce0, it's not on 1.16 yet however, only our 1.14 alpha builds.

**Comment by itsmeow** [comment] 2020-08-08 23:23
Update on this, I've identified the root cause, it's a combination of factors from what was fixed in 276c289 and a bug in IMDLib that I've just resolved. It's not fixed on 1.16 yet, but since 1.16 is purely in development and not out for public release, I'm closing this issue.

**Closed as completed by itsmeow** 2020-08-08 23:23 UTC
