### ISSUE TITLE
Crashing at hitting mob

### ISSUE THREAD

**Issue by TheButterbrotMan** [itsmeow/betteranimalsplus#295] opened 2022-01-28 16:14 UTC
## Describe what you were doing before the crash

Hiting the Ghostmob

## Crash Log (REQUIRED)

https://crashy.net/Xnd3zSWWXIS3VEDIkJ2Q

## Versions
- Minecraft Version: 1.18.1
- Architectury API Version: 3.4.9
- Platform (Forge/Fabric): Fabric
- Forge Version: /
- Fabric Loader Version: 0.12.12
- Fabric API Version: 0.46.2
- Mod Version: 11.0.3

**Comment by TheButterbrotMan** [comment] 2022-01-28 16:14
https://github.com/itsmeow/betteranimalsplus/issues/289

**Comment by itsmeow** [comment] 2022-01-28 18:00
Duplicate of #290 
Likely caused by Iris

**Closed as completed by itsmeow** 2022-01-28 18:00 UTC
