### ISSUE TITLE
Coyote stuck sitting

### ISSUE THREAD

**Issue by Nhyv** [itsmeow/betteranimalsplus#100] opened 2019-10-06 16:29 UTC
**Coyote stuck sitting** (Required)
Out of nowhere a tamed coyote got stuck sitting, doesn't eat meat and slides on the ground once in a while without following the player or attacking.

**Expected behavior** (Required)
Upon right clicking the coyote is supposed to get up (If they were sitting in the first place).

**Versions:**
 - Forge Version: 28.1.30
 - MC Version: 1.14.4
 - Mod Version: 1.14.4-7.1.2

**Comment by QuantumToasted** [comment] 2019-10-06 16:41
I'm the server owner this occurred on. I have a strange feeling this has something to do with Carry On. (Seems BA+ and Carry On don't play too nicely sometimes). This can be reproduced by picking up a sitting tamed Coyote and placing them back on the ground. They get stuck in the sitting animation/pose, but still act as normal. You can't tell whether or not they're really sitting unless they are or aren't moving.

**Comment by QuantumToasted** [comment] 2019-10-06 16:58
Another update, whether this matters at all: A temporary bandaid fix is to make your "stuck" coyote not be sitting then move far enough away to make it teleport. When it teleports it will be standing normally again.

**Comment by itsmeow** [comment] 2019-10-07 10:53
Not sure if this is a problem with CarryOn as I'm not quite sure how it works, but it looks like it's having trouble serializing the entity's state properly? Maybe @Tschipp can help? The sitting state is (de)/serialized to NBT from a datamanager byte, you can find the 1.14 code here https://github.com/itsmeow/betteranimalsplus/blob/1.14/src/main/java/its_meow/betteranimalsplus/common/entity/EntityCoyote.java keep in mind it extends https://github.com/itsmeow/betteranimalsplus/blob/1.14/src/main/java/its_meow/betteranimalsplus/common/entity/EntityFeralWolf.java which contains the sitting code as well as NBT serialization.

**Comment by Tschipp** [comment] 2019-10-08 21:18
CarryOn is extremely unstable on 1.14. I currently am very short on time and can't really look at the issues. I apologize for this.

**Comment by itsmeow** [comment] 2019-10-09 22:55
Alright. Closing here as this seems to be a CarryOn issue. If any changes are needed let me know.

**Closed by itsmeow** 2019-10-09 22:55 UTC
Labels: bug, mc:1.14, mod compat, priority:medium
