### ISSUE TITLE
Dark entities (Feral wolf/tarantula)

### ISSUE THREAD

**Issue by Krampus69** [itsmeow/betteranimalsplus#247] opened 2021-04-14 11:56 UTC
Hi!
I love your mod, it's really cool !

**Describe the bug**
Some creatures have weird textures behavior with BSL Shaders. Feral Wolf and tarantula are all black. Might have something to do with their emissive texture ?

**To Reproduce**
1. Download BSL Shaders 8.0.01
2. Spawn tarantula/feral wolf with shaders ON
3. Dab

**Expected behavior**
Textures being applied correctly.

**Screenshots**

![2021-04-14_13 48 41](https://user-images.githubusercontent.com/81943963/114705868-83c65d00-9d28-11eb-85ad-35978354966b.png)

**Versions:**
 - Minecraft Version: 1.16.5
 - Forge Version: 36.1.4
 - Mod Version: 10.1.0

**Additional context**
The bug doesn't occur with other creatures. Texture is applied correctly when no shader on. 
Also, the feral wolf has some artifacts glitches on its skin with shaders ON. Might be the reason why it's not rendering properly. Two faces with the same coordinates might the problem.

**Comment by itsmeow** [comment] 2021-04-14 23:28
Duplicate of #222

**Closed as completed by itsmeow** 2021-04-14 23:28 UTC
