### ISSUE TITLE
Crash when wandering around

### ISSUE THREAD

**Issue by TheButterbrotMan** [itsmeow/betteranimalsplus#312] opened 2022-03-06 00:14 UTC
## Describe what you were doing before the crash
Wandering around.

## Crash Log (REQUIRED)
https://bytebin.lucko.me/HarETftBll

## Versions
- Minecraft Version: 1.18.1
- Architectury API Version: 3.7.26
- Platform (Forge/Fabric): Fabric
- Forge Version:
- Fabric Loader Version: 0.13.3
- Fabric API Version: 0.46.4
- Mod Version: 11.0.4

**Comment by itsmeow** [comment] 2022-03-07 16:52
Duplicate of #306, upgrade to collective 4.9

**Closed as completed by itsmeow** 2022-03-07 16:52 UTC
