### ISSUE TITLE
Crash upon picking up entity with Carry On mod

### ISSUE THREAD

**Issue by Anatheras** [itsmeow/betteranimalsplus#160] opened 2020-04-08 03:36 UTC
**Describe what you were doing before the crash**
Tried to pick up an entity from the mod.

**To Reproduce**
1. Have "Carry On(mod version:1.12.4)"
2. Pickup birds or whales
3. See error

**Crash Log (REQUIRED)**
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 4/7/20 11:52 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at its_meow.betteranimalsplus.client.renderer.entity.RenderSongbird.doRender(RenderSongbird.java:33) ~[?:9.0.0] {re:classloading}
	at its_meow.betteranimalsplus.client.renderer.entity.RenderSongbird.func_76986_a(RenderSongbird.java:13) ~[?:9.0.0] {re:classloading}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_188391_a(EntityRendererManager.java:370) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at tschipp.carryon.client.event.RenderEntityEvents.renderEntityStatic(RenderEntityEvents.java:170) ~[?:1.0] {re:classloading}
	at tschipp.carryon.client.event.RenderEntityEvents.renderHand(RenderEntityEvents.java:120) ~[?:1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_61_RenderEntityEvents_renderHand_RenderHandEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.renderFirstPersonHand(ForgeHooksClient.java:172) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_215308_a(GameRenderer.java:442) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_181560_a(GameRenderer.java:775) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_78471_a(GameRenderer.java:640) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:494) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:890) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.2.3.jar:28.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$393/2111882926.call(Unknown Source) [forge-1.14.4-28.2.3.jar:28.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at its_meow.betteranimalsplus.client.renderer.entity.RenderSongbird.doRender(RenderSongbird.java:33)
	at its_meow.betteranimalsplus.client.renderer.entity.RenderSongbird.func_76986_a(RenderSongbird.java:13)

-- Entity being rendered --
Details:
	Entity Type: betteranimalsplus:songbird (its_meow.betteranimalsplus.common.entity.EntitySongbird)
	Entity ID: 806
	Entity Name: Songbird
	Entity's Exact location: 167.00, 72.00, -161.33
	Entity's Block location: World: (166,72,-162), Chunk: (at 6,4,14 in 10,-11; contains blocks 160,0,-176 to 175,255,-161), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: its_meow.betteranimalsplus.client.renderer.entity.RenderSongbird@200cbb63
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 0.0
	Delta: 0.0
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_188391_a(EntityRendererManager.java:370)
	at tschipp.carryon.client.event.RenderEntityEvents.renderEntityStatic(RenderEntityEvents.java:170)
	at tschipp.carryon.client.event.RenderEntityEvents.renderHand(RenderEntityEvents.java:120)
	at net.minecraftforge.eventbus.ASMEventHandler_61_RenderEntityEvents_renderHand_RenderHandEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.client.ForgeHooksClient.renderFirstPersonHand(ForgeHooksClient.java:172)
	at net.minecraft.client.renderer.GameRenderer.func_215308_a(GameRenderer.java:442)
	at net.minecraft.client.renderer.GameRenderer.func_181560_a(GameRenderer.java:775)
	at net.minecraft.client.renderer.GameRenderer.func_78471_a(GameRenderer.java:640)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Lordofthebricks'/268, l='MpServer', x=167.00, y=72.00, z=-161.33]]
	Chunk stats: Client Chunk Cache: 729, 483
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (192,66,-160), Chunk: (at 0,4,0 in 12,-10; contains blocks 192,0,-160 to 207,255,-145), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 603 game time, 603 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:410)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1750)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$393/2111882926.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1736264848 bytes (1655 MB) / 2351955968 bytes (2243 MB) up to 5628231680 bytes (5367 MB)
	CPUs: 6
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6037m -Xms256m -XX:PermSize=256m
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.5-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar fml TRANSFORMATIONSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.3
	FML Language Providers: 
		javafml@28.2
		minecraft@1
	Mod List: 
		forge-1.14.4-28.2.3-client.jar Minecraft {minecraft@1.14.4 DONE}
		CarryOn MC1.14.4 v1.12.4.jar Carry On {carryon@1.12.4 DONE}
		betteranimalsplus-1.14.4-9.0.0.jar Better Animals Plus {betteranimalsplus@9.0.0 DONE}
		forge-1.14.4-28.2.3-universal.jar Forge {forge@28.2.3 DONE}
	Launched Version: forge-28.2.3
	LWJGL: 3.2.2 build 10
	OpenGL: AMD Radeon R9 200 Series GL version 4.6.13559 Compatibility Profile Context 26.20.12028.2, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 6x AMD FX(tm)-6100 Six-Core Processor 

**Versions:**
 - OS: Windows 10 Pro version:1903 build:18362.720
 - MC Version: 1.14.4
 - Mod Version: 9.0.0
- Forge Version: 28.2.3

**Additional context**
This seems to happen with some entities like birds or whale but not with every entity, in fact so far it only works as intended with coyotes. And before you ask yourself "why would anyone want to pick up a whale?" its not that i want to pick up whales i simply tried after finding out that i couldnt pick up birds. My idea was to blacklist entities from the mod and only be able to pick up babies or small animals but then i noticed the bug.

**Comment by itsmeow** [comment] 2020-04-10 17:16
This is a duplicate because the crash in question is caused by the same issue as #159. Closing.

**Closed as completed by itsmeow** 2020-04-10 17:16 UTC
