### ISSUE TITLE
Entity Rendering issues:  Jellyfish, Pheasant, and Badgers

### ISSUE THREAD

**Issue by Mewcenary** [itsmeow/betteranimalsplus#333] opened 2022-05-12 10:18 UTC
So far Jellyfish, Pheasant, and Badgers are crashing the game.  It seems more and more animals are becoming issues every time it crashes.

[crash-2022-05-12_00.09.28-client.txt](https://github.com/itsmeow/betteranimalsplus/files/8677148/crash-2022-05-12_00.09.28-client.txt)

[crash-2022-05-12_03.11.18-client.txt](https://github.com/itsmeow/betteranimalsplus/files/8677131/crash-2022-05-12_03.11.18-client.txt)

**Comment by itsmeow** [comment] 2022-05-13 02:26
Can you try removing performant? Please also include the information in the original crash report creator such as the mod version and Forge/Architectury versions, etc.

**Comment by itsmeow** [comment] 2022-05-13 02:32
It's also possible this could be caused by "Two Players One Horse" or "Caves and Cliffs" - although I'm not certain as I can't reproduce this crash myself, and there's not enough information in the report to diagnose is the issue.

Is your modpack posted somewhere, and if not could you export the zip and post it so I can attempt to produce the crash myself?

Thanks!

**Comment by Mewcenary** [comment] 2022-05-13 04:20
architectury-1.31.61
betteranimalsplus-1.16.5-11.0.5-forge
Forge:  1.16.5-forge-36.2.35
Java: 8 - 311 (build 1.8.0_331-b09)

https://drive.google.com/drive/folders/1c8vpbqvJ78tPwwo1_aVtHuNVHYW3QoG7?usp=sharing

For some reason, it won't let me add the zip folder.  The above link is all mods originally when this started, including performent.  No change in removing performant from the server and mod list.  Hopefully I understood your directions.

Btw, I love your name XD

**Comment by Mewcenary** [comment] 2022-05-13 05:04
[Minecraft Game Output Log.txt](https://github.com/itsmeow/betteranimalsplus/files/8684206/Minecraft.Game.Output.Log.txt)

**Comment by Mewcenary** [comment] 2022-05-13 05:42
Lol the Goat now.

[crash-2022-05-12_22.40.35-client.txt](https://github.com/itsmeow/betteranimalsplus/files/8684340/crash-2022-05-12_22.40.35-client.txt)

**Comment by itsmeow** [comment] 2022-05-18 04:59
If you are using a launcher like CurseForge, you can export the pack as a ZIP file from the three dot menu. I can't access that google drive link, either. It needs to be set to public.

**Comment by itsmeow** [comment] 2022-05-18 05:09
Please try removing "Two Players one Horse" and see if this resolves your issue. I think it is very likely caused by that mod as it mixins into the LivingRenderer and seems to lack proper checks for certain states. The mod does not appear to be well made.

**Comment by itsmeow** [comment] 2022-05-26 18:25
Closing as this is the result of Two Players One Horse

**Closed as completed by itsmeow** 2022-05-26 18:25 UTC

**Comment by Mewcenary** [comment] 2022-05-30 20:31
> If you are using a launcher like CurseForge, you can export the pack as a ZIP file from the three dot menu. I can't access that google drive link, either. It needs to be set to public.

Oh sorry, I accidentally deleted it, I restored it, and it's available now.  No, I use Apex Hosting Server.  I also apologize for the delay in response, I have short-term memory loss due to a head injury.

I removed it and I still had the same issue unfortunately :/
