### ISSUE TITLE
I think a mob make me crash 

### ISSUE THREAD

**Issue by iWisd0M5d** [itsmeow/betteranimalsplus#205] opened 2020-10-05 00:51 UTC
**Describe what you were doing before the crash**
[eg. Loading game, creating world, spawning a certain mob, hurting a mob, walking around]

I was exploring the world and found some good animals and after that i crash i saw a turkey, some goats and one pheasant

**Crash Log (REQUIRED)**
https://pastebin.com/7n45Q2Hp

**Versions:**
 - Minecraft Version: 1.16.1
 - Forge Version: forge-1.16.1-32.0.108
 - Mod Version: betteranimalsplus-1.16.1-9.0.1.3

**Comment by itsmeow** [comment] 2020-10-05 00:55
Duplicate of #189

**Closed as completed by itsmeow** 2020-10-05 00:55 UTC
