### ISSUE TITLE
Rendering entity crash errors

### ISSUE THREAD

**Issue by TarnishedHart** [itsmeow/betteranimalsplus#191] opened 2020-07-30 04:33 UTC
I am using the 1.15.2 version of MC and better animals plus. I keep getting consistent crashes. I even restarted my server. I am wondering if there is a mod conflict. I don't know how to figure this out as I tried messing around with the different mods and I haven't been able to come to any conclusions. I also can't understand the crash reports at all. All I know is, the game WILL crash after a while. And in each crash report it says something about rendering a better animals plus creature. So, here are two of the most recent crash reports. These two happened one after the of other. I hope I 

Crash Log 1.
[crash-2020-07-29_21.37.58-client.txt](https://github.com/itsmeow/betteranimalsplus/files/4998791/crash-2020-07-29_21.37.58-client.txt)

- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 7/29/20 9:37 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at its_meow.betteranimalsplus.client.renderer.entity.RenderShark.render(RenderShark.java:36) ~[?:8.2.1.96] {re:classloading}
	at its_meow.betteranimalsplus.client.renderer.entity.RenderShark.func_225623_a_(RenderShark.java:14) ~[?:8.2.1.96] {re:classloading}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:305) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1855) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:388) ~[?:?] {re:classloading}
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4252) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:926) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:686) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:924) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.15.2-31.2.31.jar:31.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$433/1901700557.call(Unknown Source) [forge-1.15.2-31.2.31.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at its_meow.betteranimalsplus.client.renderer.entity.RenderShark.render(RenderShark.java:36)
	at its_meow.betteranimalsplus.client.renderer.entity.RenderShark.func_225623_a_(RenderShark.java:14)

-- Entity being rendered --
Details:
	Entity Type: betteranimalsplus:shark (its_meow.betteranimalsplus.common.entity.EntityShark)
	Entity ID: 192045
	Entity Name: Shark
	Entity's Exact location: 23.44, 58.25, -2.18
	Entity's Block location: World: (23,58,-3), Chunk: (at 7,3,13 in 1,-1; contains blocks 16,0,-16 to 31,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: -0.08, -0.00, -0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: its_meow.betteranimalsplus.client.renderer.entity.RenderShark@25e331ff
	Location: 13.30,-25.94,-62.73 - World: (13,-26,-63), Chunk: (at 13,-2,1 in 0,-4; contains blocks 0,0,-64 to 15,255,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Rotation: 92.8125
	Delta: 0.68007433
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:305)
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1855)
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:388)
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4252)
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:926)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['WrathWhispered'/190777, l='MpServer', x=2.64, y=63.94, z=61.16]]
	Chunk stats: Client Chunk Cache: 225, 104
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 3015501214151837185
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-240,67,-128), Chunk: (at 0,4,0 in -15,-8; contains blocks -240,0,-128 to -225,255,-113), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 5993540 game time, 7346065 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:611)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1763)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:567)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$433/1901700557.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3104235336 bytes (2960 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 6
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.31.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.31.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.31.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.31.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.15.2_HD_U_G1_pre26.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.31.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.31
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		forge-1.15.2-31.2.31-client.jar Minecraft {minecraft@1.15.2 DONE}
		gun-mod-0.16.1-1.15.2.jar MrCrayfish's Gun Mod {cgm@0.16.1 DONE}
		BiomesOPlenty-1.15.2-10.0.0.363-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.363 DONE}
		jei-1.15.2-6.0.2.12.jar Just Enough Items {jei@6.0.2.12 DONE}
		FallingTree-1.15.2-2.1.7.jar Falling Tree {falling_tree@2.1.7 DONE}
		DoggyTalents-1.15.2-1.15.2.3.jar Doggy Talents {doggytalents@1.15.2.3 DONE}
		flying_things-1.8.9-1.15.2.jar The Flying Things {flying_things@1.8.9 DONE}
		Xaeros_Minimap_20.18.0.1_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.18.0 DONE}
		timber-1.15.2-1.5.jar Timber Mod {timber@1.5 DONE}
		gravestone-1.17.5.jar Gravestone Mod {gravestone@1.17.5 DONE}
		XaerosWorldMap_1.8.1_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.8.1 DONE}
		horse_colors-1.15.2-1.3.6.jar Realistic Horse Genetics {horse_colors@1.15.2-1.3.6 DONE}
		[1.15.2]+SecurityCraft+v1.8.19.1.jar SecurityCraft {securitycraft@v1.8.19.1 DONE}
		obfuscate-0.4.3-1.15.2.jar Obfuscate {obfuscate@0.4.3 DONE}
		betteranimalsplus-1.15.2-8.2.1.96.jar Better Animals Plus {betteranimalsplus@8.2.1.96 DONE}
		structurize-0.13.19-ALPHA.jar Structurize {structurize@0.13.19-ALPHA DONE}
		Bookshelf-1.15.2-5.6.40.jar Bookshelf {bookshelf@5.6.40 DONE}
		Reliquary-1.15.2-1.3.4.995.jar Reliquary {xreliquary@1.15.2-1.3.4.995 DONE}
		minecolonies-0.13.44-BETA-universal.jar Minecolonies {minecolonies@0.13.44-BETA DONE}
		simpleplanes-1.15.2-2.0.3.0.jar Simple Planes {simpleplanes@2.0.3.0 DONE}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		advancedtools-1.15.2-1.0.2.jar Advanced Tools {advancedtools@1.15.2-1.0.2 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		WAWLA-1.15.2-3.0.4.jar WAWLA {wawla@3.0.4 DONE}
		forge-1.15.2-31.2.31-universal.jar Forge {forge@31.2.31 DONE}
		CosmeticArmorReworked-1.15.2-v3a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.15.2-v3a DONE}
		lumberjack-2.0.1.jar LumberJack {lumberjack@2.0.1 DONE}
	Launched Version: 1.15.2-forge-31.2.31
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 451.67, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, mod_resources, file/Round+Trees+2.8+ยง31.15+ยงo.zip, file/Dramatic+Sky+for+1.14+.zip, file/PureBDcraft 128x MC115.zip, file/Sphax128x_BOP_MC1.15.zip
	Current Language: English (US)
	CPU: 6x Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre26
	OptiFine Build: 20200615-011655
	Render Distance Chunks: 15
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.27 High.zip
	OpenGlVersion: 4.6.0 NVIDIA 451.67
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 6

Crash Log 2.

[crash-2020-07-29_22.13.59-client.txt](https://github.com/itsmeow/betteranimalsplus/files/4998793/crash-2020-07-29_22.13.59-client.txt)

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 7/29/20 10:13 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at its_meow.betteranimalsplus.client.renderer.entity.RenderWhale.render(RenderWhale.java:37) ~[?:8.2.1.96] {re:classloading}
	at its_meow.betteranimalsplus.client.renderer.entity.RenderWhale.func_225623_a_(RenderWhale.java:14) ~[?:8.2.1.96] {re:classloading}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:305) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1855) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:388) ~[?:?] {re:classloading}
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4252) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:926) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:686) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:924) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.15.2-31.2.31.jar:31.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$422/1109461985.call(Unknown Source) [forge-1.15.2-31.2.31.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at its_meow.betteranimalsplus.client.renderer.entity.RenderWhale.render(RenderWhale.java:37)
	at its_meow.betteranimalsplus.client.renderer.entity.RenderWhale.func_225623_a_(RenderWhale.java:14)

-- Entity being rendered --
Details:
	Entity Type: betteranimalsplus:whale (its_meow.betteranimalsplus.common.entity.EntityWhale)
	Entity ID: 195271
	Entity Name: Whale
	Entity's Exact location: 20.50, 53.00, 7.50
	Entity's Block location: World: (20,53,7), Chunk: (at 4,3,7 in 1,0; contains blocks 16,0,0 to 31,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: its_meow.betteranimalsplus.client.renderer.entity.RenderWhale@661239e8
	Location: -8.13,-7.62,-33.57 - World: (-9,-8,-34), Chunk: (at 7,-1,14 in -1,-3; contains blocks -16,0,-48 to -1,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Rotation: 90.0
	Delta: 0.020092726
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:305)
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1855)
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:388)
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4252)
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:926)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['WrathWhispered'/192160, l='MpServer', x=28.63, y=59.00, z=41.07]]
	Chunk stats: Client Chunk Cache: 225, 127
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 3015501214151837185
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-240,67,-128), Chunk: (at 0,4,0 in -15,-8; contains blocks -240,0,-128 to -225,255,-113), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 6036763 game time, 7400630 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:611)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1763)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:567)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$422/1109461985.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3772683128 bytes (3597 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 6
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.31.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.31.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.31.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.31.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.15.2_HD_U_G1_pre26.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.31.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.31
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		forge-1.15.2-31.2.31-client.jar Minecraft {minecraft@1.15.2 DONE}
		gun-mod-0.16.1-1.15.2.jar MrCrayfish's Gun Mod {cgm@0.16.1 DONE}
		BiomesOPlenty-1.15.2-10.0.0.363-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.363 DONE}
		jei-1.15.2-6.0.2.12.jar Just Enough Items {jei@6.0.2.12 DONE}
		FallingTree-1.15.2-2.1.7.jar Falling Tree {falling_tree@2.1.7 DONE}
		DoggyTalents-1.15.2-1.15.2.3.jar Doggy Talents {doggytalents@1.15.2.3 DONE}
		flying_things-1.8.9-1.15.2.jar The Flying Things {flying_things@1.8.9 DONE}
		Xaeros_Minimap_20.18.0.1_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.18.0 DONE}
		timber-1.15.2-1.5.jar Timber Mod {timber@1.5 DONE}
		gravestone-1.17.5.jar Gravestone Mod {gravestone@1.17.5 DONE}
		XaerosWorldMap_1.8.1_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.8.1 DONE}
		horse_colors-1.15.2-1.3.6.jar Realistic Horse Genetics {horse_colors@1.15.2-1.3.6 DONE}
		[1.15.2]+SecurityCraft+v1.8.19.1.jar SecurityCraft {securitycraft@v1.8.19.1 DONE}
		obfuscate-0.4.3-1.15.2.jar Obfuscate {obfuscate@0.4.3 DONE}
		betteranimalsplus-1.15.2-8.2.1.96.jar Better Animals Plus {betteranimalsplus@8.2.1.96 DONE}
		structurize-0.13.19-ALPHA.jar Structurize {structurize@0.13.19-ALPHA DONE}
		Bookshelf-1.15.2-5.6.40.jar Bookshelf {bookshelf@5.6.40 DONE}
		Reliquary-1.15.2-1.3.4.995.jar Reliquary {xreliquary@1.15.2-1.3.4.995 DONE}
		minecolonies-0.13.44-BETA-universal.jar Minecolonies {minecolonies@0.13.44-BETA DONE}
		simpleplanes-1.15.2-2.0.3.0.jar Simple Planes {simpleplanes@2.0.3.0 DONE}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		advancedtools-1.15.2-1.0.2.jar Advanced Tools {advancedtools@1.15.2-1.0.2 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		WAWLA-1.15.2-3.0.4.jar WAWLA {wawla@3.0.4 DONE}
		forge-1.15.2-31.2.31-universal.jar Forge {forge@31.2.31 DONE}
		CosmeticArmorReworked-1.15.2-v3a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.15.2-v3a DONE}
		lumberjack-2.0.1.jar LumberJack {lumberjack@2.0.1 DONE}
	Launched Version: 1.15.2-forge-31.2.31
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 451.67, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, mod_resources, file/Round+Trees+2.8+ยง31.15+ยงo.zip, file/Dramatic+Sky+for+1.14+.zip, file/PureBDcraft 128x MC115.zip, file/Sphax128x_BOP_MC1.15.zip
	Current Language: English (US)
	CPU: 6x Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre26
	OptiFine Build: 20200615-011655
	Render Distance Chunks: 15
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.27 High.zip
	OpenGlVersion: 4.6.0 NVIDIA 451.67
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 6

Thank you for this wonderful mod and thank you for your time,
TH

**Comment by itsmeow** [comment] 2020-07-30 04:36
Duplicate of #165

**Closed as completed by itsmeow** 2020-07-30 04:36 UTC
