### ISSUE TITLE
Crash due to walrus

### ISSUE THREAD

**Issue by RaashDE** [itsmeow/betteranimalsplus#215] opened 2020-12-10 21:27 UTC
**Describe what you were doing before the crash**
Walking around the world, suddenly the game crashes
"The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Ticking entity
Exit Code: -1"

**To Reproduce**
Walk around in world

**Crash Log (REQUIRED)**
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 12/10/20 10:22 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.pathfinding.PathFinder.func_227478_a_(SourceFile:550) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:performant.mixins.json:pathing.PathFinderMixin,pl:mixin:A}
	at net.minecraft.pathfinding.PathNavigator.func_225464_a(PathNavigator.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:pathing.PathNavigatorMixin,pl:mixin:A}
	at net.minecraft.pathfinding.PathNavigator.func_179680_a(PathNavigator.java:102) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:pathing.PathNavigatorMixin,pl:mixin:A}
	at net.minecraft.pathfinding.PathNavigator.func_225466_a(PathNavigator.java:92) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:pathing.PathNavigatorMixin,pl:mixin:A}
	at net.minecraft.pathfinding.PathNavigator.func_75492_a(PathNavigator.java:138) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:pathing.PathNavigatorMixin,pl:mixin:A}
	at net.minecraft.entity.ai.goal.MoveToBlockGoal.func_220725_g(SourceFile:67) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.entity.ai.goal.MoveToBlockGoal.func_75249_e(SourceFile:61) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75249_e(SourceFile:41) ~[?:?] {re:classloading}
	at com.performant.coremod.entity.ai.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:363) ~[?:1.15-3.11m] {re:classloading}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:856) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2262) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches LivingEntity Transformer,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:1927) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A}
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:159) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(SourceFile:44) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2104) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches LivingEntity Transformer,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:397) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600) ~[?:?] {re:mixin,re:classloading,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook,pl:mixin:APP:assets/fruittrees/fruittrees.mixins.json:MixinServerWorld,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld$$Lambda$12435/1689639359.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:536) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.WorldMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401) ~[?:?] {re:mixin,re:classloading,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook,pl:mixin:APP:assets/fruittrees/fruittrees.mixins.json:MixinServerWorld,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:163) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.pathfinding.PathFinder.func_227478_a_(SourceFile:550)
	at net.minecraft.pathfinding.PathNavigator.func_225464_a(PathNavigator.java:607)
	at net.minecraft.pathfinding.PathNavigator.func_179680_a(PathNavigator.java:102)
	at net.minecraft.pathfinding.PathNavigator.func_225466_a(PathNavigator.java:92)
	at net.minecraft.pathfinding.PathNavigator.func_75492_a(PathNavigator.java:138)
	at net.minecraft.entity.ai.goal.MoveToBlockGoal.func_220725_g(SourceFile:67)
	at net.minecraft.entity.ai.goal.MoveToBlockGoal.func_75249_e(SourceFile:61)
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75249_e(SourceFile:41)
	at com.performant.coremod.entity.ai.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:363)
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:856)
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2262)
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:1927)
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:159)
	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(SourceFile:44)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2104)
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:397)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600)
	at net.minecraft.world.server.ServerWorld$$Lambda$12435/1689639359.accept(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: betteranimalsplus:walrus (its_meow.betteranimalsplus.common.entity.EntityWalrus)
	Entity ID: 2425
	Entity Name: Walrus
	Entity's Exact location: -3447.00, 64.00, -2501.00
	Entity's Block location: World: (-3447,64,-2501), Chunk: (at 9,4,11 in -216,-157; contains blocks -3456,0,-2512 to -3441,255,-2497), Region: (-7,-5; contains chunks -224,-160 to -193,-129, blocks -3584,0,-2560 to -3073,255,-2049)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:536)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['RaashDE'/123, l='Survival', x=-3386.87, y=64.25, z=-2305.80]]
	Chunk stats: ServerChunkCache: 4626
	Level dimension: DimensionType{minecraft:overworld}
	Level name: Survival
	Level seed: -5281935410807522916
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (-64,68,80), Chunk: (at 0,4,0 in -4,5; contains blocks -64,0,80 to -49,255,95), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 434167 game time, 1425 day time
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 94151 (now: false), thunder time: 51392 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:163)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 790087320 bytes (753 MB) / 3672113152 bytes (3502 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m -XX:PermSize=256m
	ModLauncher: 5.1.2+70+master.2845bb9
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.45.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.45.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.45.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.45.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/preview_OptiFine_1.15.2_HD_U_G5_pre1.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.45.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.5.jar mixinbootstrap TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.45
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		NetherPortalFix_1.15.2-6.0.2.jar NetherPortalFix {netherportalfix@6.0.2 DONE}
		refinedpipes-0.4.2.jar Refined Pipes {refinedpipes@0.4.2 DONE}
		DoggyTalents-1.15.2-1.15.2.3.jar Doggy Talents {doggytalents@1.15.2.3 DONE}
		mcws-win-1.15.2-v1.0.2.jar Macaw's Windows {mcwwindows@1.0.2 DONE}
		SilentMechanisms-1.15.2-0.8.0+59.jar Silent's Mechanisms {silents_mechanisms@0.8.0+59 DONE}
		Industrial Agriculture[Core]-1.15.2-1.7.0.jar Industrial Agriculture {industrialagriculture@1.15.2-1.7.0 DONE}
		strawgolem-1.15.2-1.9.jar Straw Golem {strawgolem@1.15.2-1.9 DONE}
		essentials-1.15.2-2.7.4.jar Essentials {essentials@1.15.2-2.7.4 DONE}
		Placebo-1.15.2-3.1.0.jar Placebo {placebo@3.1.0 DONE}
		NamePain-1.3.0_Forge-1.15.2.jar Name Pain {namepain@1.3.0 DONE}
		theloader-1.15.2-1.1.0.jar The Loader {theloader@1.15.2-1.1.0 DONE}
		u_team_core-1.15.2-3.0.2.169.jar U Team Core {uteamcore@3.0.2.169 DONE}
		randompatches-1.15.2-1.22.1.1.jar RandomPatches {randompatches@1.15.2-1.22.1.1 DONE}
		buildinggadgets-3.4.0.jar Building Gadgets {buildinggadgets@3.4.0 DONE}
		ProgressiveBosses-2.1.5-mc1.15.2.jar Progressive Bosses {progressivebosses@2.1.5-mc1.15.2 DONE}
		mcw-doors-1.0.1fix-mc1.15.1-2.jar Macaw's Doors {mcwdoors@1.0.1 DONE}
		Morpheus-1.15.2-4.2.50.jar Morpheus {morpheus@version DONE}
		MekanismGenerators-1.15.2-9.10.9.422.jar Mekanism: Generators {mekanismgenerators@9.10.9 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		SnowRealMagic-1.15.2-1.7.5.jar Snow! Real Magic! {snowrealmagic@1.7.5 DONE}
		refinedstorage-1.8.8.jar Refined Storage {refinedstorage@1.8.8 DONE}
		PackMenu-1.15.2-1.2.8.jar Pack Menu {packmenu@1.2.8 DONE}
		mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
		useful_backpacks-1.15.2-1.10.3.77.jar Useful Backpacks {usefulbackpacks@1.10.3.77 DONE}
		AmbientSounds_v3.0.20_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		Industrial Agriculture[Silent's Mechanisms]-1.15.2-1.6.1.jar Industrial Agriculture Plugin-Silent's Mechanisms {iapsm@1.15.2-1.6.1 DONE}
		BiomesOPlenty-1.15.2-10.0.0.366-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.366 DONE}
		phosphor-forge-mc1.15.2-0.5.2+build.4.jar Phosphor {phosphor@0.5.2+build.4 DONE}
		Blur-1.1.0-1.jar Blur {blur@1.1.0-1 DONE}
		valhelsia_structures-15.0.3a.jar Valhelsia Structures {valhelsia_structures@15.0.3a DONE}
		mining_dimension-1.15.2-1.0.4.jar Mining World {mining_dimension@1.15.2-1.0.4 DONE}
		SilentGear-1.15.2-1.11.3+160.jar Silent Gear {silentgear@1.11.3+160 DONE}
		simplefarming-1.15.2-1.3.3.jar Simple Farming {simplefarming@1.15.1-1.3.3 DONE}
		MysticalAdaptations-1.15.2-1.2.3.jar Mystical Adaptations {mysticaladaptations@NONE DONE}
		MysticalAgradditions-1.15.2-3.0.1.jar Mystical Agradditions {mysticalagradditions@3.0.1 DONE}
		curios-FORGE-1.15.2-2.0.2.6.jar Curios API {curios@FORGE-1.15.2-2.0.2.6 DONE}
		Patchouli-1.15.2-1.2-35.jar Patchouli {patchouli@1.15.2-1.2-35 DONE}
		config-2-3.0.jar Cloth Config v2 API {cloth-config2@3.0 DONE}
		OreExcavation-1.7.151.jar Ore Excavation {oreexcavation@NONE DONE}
		libnonymous-1.15.2-1.1.1.5.jar Libnonymous {libnonymous@1.1.1.5 DONE}
		elevatorid-1.15.2-1.7.1.jar Elevator Mod {elevatorid@1.15.2-1.7.1 DONE}
		obfuscate-0.5.0-1.15.2.jar Obfuscate {obfuscate@0.5.0 DONE}
		NaturesAura-28.5.jar Nature's Aura {naturesaura@28.5 DONE}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		mcw-furniture-1.0.1-mc1.15.1 1.15.2.jar Macaw's Furnitures {mcwfurnitures@1.0.1 DONE}
		the_bumblezone-1.15.2-1.3.10.jar The Bumblezone {the_bumblezone@1.15.2-1.3.10 DONE}
		FastLeafDecay-v22.1.jar FastLeafDecay {fastleafdecay@v22.1 DONE}
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 DONE}
		Cucumber-1.15.2-3.0.9.jar Cucumber Library {cucumber@3.0.9 DONE}
		mining-helmet-1.15.2-1.0.9.jar Mining Helmet {mining_helmet@1.0.9 DONE}
		jei-1.15.2-6.0.3.15.jar Just Enough Items {jei@6.0.3.15 DONE}
		FallingTree-1.15.2-2.4.0.jar Falling Tree {falling_tree@2.4.0 DONE}
		fishtraps-forge-1.15.2-0.0.5.jar Fish Traps {fishtraps@1.14.4-0.0.4 DONE}
		Abnormals-Core-1.15.2-1.0.6.jar Abnormals Core {abnormals_core@1.0.6 DONE}
		Buzzier-Bees-1.15.2-1.5.2.jar Buzzier Bees {buzzierbees@1.5.2 DONE}
		KiwiBirds 1.3 1.15.2.jar Kiwi Birds {kiwibirds@1.2 1.15.2 DONE}
		goblintraders-1.2.0-1.15.2.jar Goblin Traders {goblintraders@1.2.0 DONE}
		Mekanism-1.15.2-9.10.9.422.jar Mekanism {mekanism@9.10.9 DONE}
		Waystones_1.15.2-6.0.2.jar Waystones {waystones@6.0.2 DONE}
		goldenhopper-1.1.1-1.15.2.jar Golden Hopper {goldenhopper@1.1.1 DONE}
		light-overlay-4.7.2.jar Light Overlay Forge {lightoverlay-forge@NONE DONE}
		journeymap-1.15.2-5.7.0b3.jar Journeymap {journeymap@5.7.0b3 DONE}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 DONE}
		FruitTrees-1.15.2-1.6.0.jar Fruit Trees {fruittrees@1.6.0 DONE}
		Kiwi-1.15.2-2.8.2.jar Kiwi {kiwi@2.8.2 DONE}
		VanillaTweaks-1.15.2.1.5.30.jar VanillaTweaks {vanillatweaks@1.15.2.1.5.30 DONE}
		DefaultSettings-1.14.x-1.15.2-2.2.0.jar DefaultSettings {defaultsettings@2.2.0 DONE}
		betteranimalsplus-1.15.2-10.0.0.jar Better Animals Plus {betteranimalsplus@10.0.0 DONE}
		snowundertrees-1.15.2-v1.1.1.jar Snow Under Trees {snowundertrees@v1.1.1 DONE}
		BonsaiTrees-2.1.2.6.jar Bonsai Trees 2 {bonsaitrees2@2.1.2.6 DONE}
		JEITweaker-1.15.2-1.0.1.3.jar JEI Tweaker {jeitweaker@1.0.1.3 DONE}
		CraftTweaker-1.15.2-6.0.0.24.jar CraftTweaker {crafttweaker@6.0.0.24 DONE}
		Swamp-Expansion-1.15.2-1.7.3.jar Swamp Expansion {swampexpansion@NONE DONE}
		forge-1.15.2-31.2.45-universal.jar Forge {forge@31.2.45 DONE}
		Waddles-1.15.2-0.8.6.jar Waddles {waddles@1.15.2-0.8.6 DONE}
		MysticalAgriculture-1.15.2-3.0.10.jar Mystical Agriculture {mysticalagriculture@3.0.10 DONE}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 DONE}
		CraftingTweaks_1.15.2-11.0.1.jar Crafting Tweaks {craftingtweaks@11.0.1 DONE}
		forge-1.15.2-31.2.45-client.jar Minecraft {minecraft@1.15.2 DONE}
		The-Endergetic-Expansion-1.15.2-v1.3.2.jar The Endergetic Expansion {endergetic@1.3.2 DONE}
		swingthroughgrass-1.15.2-1.4.1.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.1 DONE}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		SilentLib-1.15.2-4.6.6+59.jar Silent Lib {silentlib@4.6.6+59 DONE}
		morevanillalib-1.15.2-1.2.2.jar MoreVanillaLib {morevanillalib@1.2.2 DONE}
		JAOPCA-1.15.2-3.2.0.15.jar JAOPCA {jaopca@3.2.0.15 DONE}
		gravestone-1.17.5.jar Gravestone Mod {gravestone@1.17.5 DONE}
		autumnity-1.3.3-1.15.2.jar Autumnity {autumnity@1.3.3 DONE}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 DONE}
		Quark-r2.1-245.jar Quark {quark@r2.1-245 DONE}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 DONE}
		performant-1.15-3.11m.jar Performant {performant@3.11m DONE}
		vanillahammers-1.15.2-2.1.jar Vanilla Hammers {vanillahammers@2.1 DONE}
		themidnight-0.5.9.jar The Midnight {midnight@0.5.9 DONE}
		PickleTweaks-1.15.2-4.0.4.jar Pickle Tweaks {pickletweaks@4.0.4 DONE}
		AppleSkin-mc1.15.2-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
		Aquaculture-1.15.2-2.0.21.jar Aquaculture 2 {aquaculture@1.15.2-2.0.21 DONE}
		Industrial Agriculture[Mekanism]-1.15.2-1.6.1.jar Industrial Agriculture Plugin-Mekanism {iapmekanism@1.15.2-1.6.1 DONE}
		refinedstorageaddons-0.6.3.jar Refined Storage Addons {refinedstorageaddons@0.6.3 DONE}
		SolarGeneration-1.15.2-1.2.2.jar Solar Generation {solargeneration@1.2.2 DONE}
		SoundFilters-0.14_for_1.15.2.jar Sound Filters {soundfilters@0.14_for_1.15.2 DONE}
	Kiwi Modules: 
		fruittrees:cherry
		fruittrees:fruittrees
		fruittrees:hybridization
		kiwi:contributors
		kiwi:data
		snowrealmagic:snowrealmagic
	Patchouli open book context: n/a
	Player Count: 1 / 8; [ServerPlayerEntity['RaashDE'/123, l='Survival', x=-3386.87, y=64.25, z=-2305.80]]
	Data Packs: mod:betteranimalsplus (incompatible), vanilla, inmemory:jaopca (incompatible), mod:netherportalfix (incompatible), mod:refinedpipes, mod:doggytalents (incompatible), mod:mcwwindows, mod:silents_mechanisms (incompatible), mod:industrialagriculture (incompatible), mod:strawgolem, mod:essentials (incompatible), mod:placebo (incompatible), mod:namepain, mod:theloader (incompatible), mod:uteamcore, mod:randompatches (incompatible), mod:buildinggadgets (incompatible), mod:progressivebosses, mod:mcwdoors, mod:morpheus (incompatible), mod:mekanismgenerators, mod:waila (incompatible), mod:snowrealmagic, mod:refinedstorage (incompatible), mod:packmenu (incompatible), mod:mcwbridges, mod:usefulbackpacks, mod:ambientsounds (incompatible), mod:iapsm (incompatible), mod:biomesoplenty, mod:phosphor, mod:blur (incompatible), mod:valhelsia_structures (incompatible), mod:mining_dimension, mod:silentgear (incompatible), mod:simplefarming, mod:mysticaladaptations (incompatible), mod:mysticalagradditions, mod:curios (incompatible), mod:patchouli (incompatible), mod:cloth-config2 (incompatible), mod:oreexcavation (incompatible), mod:libnonymous (incompatible), mod:elevatorid, mod:obfuscate (incompatible), mod:naturesaura (incompatible), mod:cfm (incompatible), mod:aiimprovements (incompatible), mod:mcwfurnitures, mod:the_bumblezone, mod:fastleafdecay, mod:inventorysorter (incompatible), mod:cucumber, mod:mining_helmet (incompatible), mod:jei (incompatible), mod:falling_tree, mod:fishtraps (incompatible), mod:abnormals_core, mod:buzzierbees, mod:kiwibirds, mod:goblintraders, mod:mekanism, mod:waystones (incompatible), mod:goldenhopper, mod:lightoverlay-forge (incompatible), mod:journeymap (incompatible), mod:naturescompass (incompatible), mod:fruittrees, mod:kiwi, mod:vanillatweaks, mod:defaultsettings (incompatible), mod:snowundertrees (incompatible), mod:bonsaitrees2, mod:jeitweaker, mod:crafttweaker (incompatible), mod:swampexpansion (incompatible), mod:forge (incompatible), mod:waddles (incompatible), mod:mysticalagriculture, mod:ironchest, mod:craftingtweaks (incompatible), mod:endergetic (incompatible), mod:swingthroughgrass (incompatible), mod:mousetweaks (incompatible), mod:silentlib (incompatible), mod:morevanillalib, mod:jaopca (incompatible), mod:gravestone, mod:autumnity, mod:autoreglib (incompatible), mod:quark, mod:storagedrawers (incompatible), mod:performant (incompatible), mod:vanillahammers, mod:midnight, mod:pickletweaks, mod:appleskin (incompatible), mod:aquaculture, mod:iapmekanism, mod:refinedstorageaddons (incompatible), mod:solargeneration, mod:soundfilters (incompatible), the_loader/SGear-Basic-Metals-v1.3.zip
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.15.2_HD_U_G5_pre1
	OptiFine Build: 20201107-171351
	Render Distance Chunks: 14
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 460.79
	OpenGlRenderer: GeForce GTX 980 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Versions:**
 - Minecraft Version: 1.12.2
 - Forge Version: 31.2.45
 - Mod Version: 10.0.0

**Additional context**
X

**Comment by RaashDE** [comment] 2020-12-10 21:30
After the first time Ioaded the save without the mod enabled, quit the game and enabled it again, worked for ~3 Minutes then same crash

**Comment by itsmeow** [comment] 2020-12-10 21:31
Duplicate of #201, You will have to disable or remove performant, or disable spawning of walruses in the BAP config. This is purely a performant issue, nothing we can do.

**Closed as completed by itsmeow** 2020-12-10 21:31 UTC

**Comment by RaashDE** [comment] 2020-12-10 21:32
Thx

**Comment by itsmeow** [comment] 2020-12-10 21:33
Also try updating to performant 3.12

**Comment by Spongman** [comment] 2020-12-14 07:46
> disable spawning of walruses in the BAP config

are there any instructions anywhere on how to do this?

**Comment by itsmeow** [comment] 2020-12-15 05:56
@Spongman Open the config file (location is in the FAQ), find
```toml
[entities]
	# ...
	[entities.walrus]
		# Disables natural spawning
		doSpawning = true
	# ...
```
and change `true` to `false`.

You might also need to kill any loaded walruses while performant is disabled, because previously spawned ones will continue to exist. You can use `/kill @e[type=betteranimalsplus:walrus]` to kill all loaded walruses. If they're not loaded (no player is near them) there's not much you can do. Honestly, just go yell at the performant dev if the 3.12 update didn't fix anything. https://github.com/someaddons/performant_issues/issues/23

**Comment by Spongman** [comment] 2020-12-15 05:57
thanks!

actually, i did end up just disabling performant and eventually i found the walruses that were triggering the crashes ;-)
