### ISSUE TITLE
[1.15.2] MultiMC clinet crash - Rendering Shark

### ISSUE THREAD

**Issue by rickspencer** [itsmeow/betteranimalsplus#190] opened 2020-07-16 12:44 UTC
**Describe what you were doing before the crash**
building underwater base in Deep Ocean

**To Reproduce**
Steps to reproduce the behaviour (if possible):
Happens randomly but regularly so just spend 10 to 20 mins underwater in the same area.
I've been building a massive underwater base for the past 5 days and it's happened about 10 times now.

**Crash Log (REQUIRED)**
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 16/07/20 10:27 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at its_meow.betteranimalsplus.client.renderer.entity.RenderShark.render(RenderShark.java:36) ~[?:8.2.1.96] {re:classloading}
	at its_meow.betteranimalsplus.client.renderer.entity.RenderShark.func_225623_a_(RenderShark.java:14) ~[?:8.2.1.96] {re:classloading}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:245) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:add-render,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1094) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:journeymap:WorldRenderer.markForRerender,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:948) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:journeymap:WorldRenderer.markForRerender,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:600) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:422) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:924) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:codechickenlib:IItemRenderer,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:codechickenlib:IItemRenderer,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) ~[minecraft-1.15.2-client.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.15.2-31.2.22-launcher.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {re:classloading}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:39) [ForgeWrapper-1.4.1.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at its_meow.betteranimalsplus.client.renderer.entity.RenderShark.render(RenderShark.java:36)
	at its_meow.betteranimalsplus.client.renderer.entity.RenderShark.func_225623_a_(RenderShark.java:14)

-- Entity being rendered --
Details:
	Entity Type: betteranimalsplus:shark (its_meow.betteranimalsplus.common.entity.EntityShark)
	Entity ID: 1844258
	Entity Name: Shark
	Entity's Exact location: -1212670.50, 57.00, -1208232.50
	Entity's Block location: World: (-1212671,57,-1208233), Chunk: (at 1,3,7 in -75792,-75515; contains blocks -1212672,0,-1208240 to -1212657,255,-1208225), Region: (-2369,-2360; contains chunks -75808,-75520 to -75777,-75489, blocks -1212928,0,-1208320 to -1212417,255,-1207809)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: its_meow.betteranimalsplus.client.renderer.entity.RenderShark@5e801621
	Location: -102.04,19.38,19.06 - World: (-103,19,19), Chunk: (at 9,1,3 in -7,1; contains blocks -112,0,16 to -97,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Rotation: 26.71875
	Delta: 0.40047485
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:245)
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1094)
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:948)
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:600)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['MasterElroco'/1831430, l='MpServer', x=-1212568.46, y=36.00, z=-1208251.56]]
	Chunk stats: Client Chunk Cache: 1369, 1023
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 4061095365208375008
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (208,64,64), Chunk: (at 0,4,0 in 13,4; contains blocks 208,0,64 to 223,255,79), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 114331923 game time, 12238573 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:442)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1763)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:567)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 21107491048 bytes (20129 MB) / 25124929536 bytes (23961 MB) up to 30542397440 bytes (29127 MB)
	CPUs: 8
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms16384m -Xmx32768m
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.22-launcher.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.22-launcher.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.22-launcher.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.22-launcher.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.2.22-launcher.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.22
	FML Language Providers: 
		javafml@31.2
		minecraft@1
		kotlinfml@1.5.2
	Mod List: 
		CyclopsCore-1.15.2-1.7.0.jar Cyclops Core {cyclopscore@1.7.0 DONE}
		NetherPortalFix_1.15.2-6.0.2.jar NetherPortalFix {netherportalfix@6.0.2 DONE}
		zombiehs_1.15-2.4.jar Zombie Horse Spawn {zombiehs@2.4 DONE}
		refinedpipes-0.4.2.jar Refined Pipes {refinedpipes@0.4.2 DONE}
		DoggyTalents-1.15.2-1.15.2.3.jar Doggy Talents {doggytalents@1.15.2.3 DONE}
		paperbooks_1.15-1.1.jar Paper Books {paperbooks@1.1 DONE}
		SilentMechanisms-1.15.2-0.7.2+52.jar Silent's Mechanisms {silents_mechanisms@0.7.2+52 DONE}
		guiclock_1.15-1.8.jar GUI Clock {guiclock@1.8 DONE}
		rsgauges-1.15.2-1.2.3.jar Gauges and Switches {rsgauges@1.2.3 DONE}
		essentials-1.15.2-2.7.2.jar Essentials {essentials@1.15.2-2.7.2 DONE}
		ForgeEndertech-1.15.2-6.0.3.2-build.0042.jar Forge Endertech {forgeendertech@6.0.3.2 DONE}
		CookingForBlockheads_1.15.2-8.0.3.jar Cooking for Blockheads {cookingforblockheads@8.0.3 DONE}
		Controlling-6.1.5.6.jar Controlling {controlling@6.1.5.6 DONE}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 DONE}
		NamePain-1.15.2-Forge-1.2.2.jar Name Pain {namepain@1.2.2 DONE}
		Powah-1.15.2-1.1.14.jar Powah {powah@1.1.14 DONE}
		theloader-1.15.2-1.1.0.jar The Loader {theloader@1.15.2-1.1.0 DONE}
		Bookshelf-1.15.2-5.6.40.jar Bookshelf {bookshelf@5.6.40 DONE}
		Reliquary-1.15.2-1.3.4.995.jar Reliquary {xreliquary@1.15.2-1.3.4.995 DONE}
		u_team_core-1.15.2-2.12.1.158.jar U Team Core {uteamcore@2.12.1.158 DONE}
		randompatches-1.15.2-1.21.1.2.jar RandomPatches {randompatches@1.15.2-1.21.1.2 DONE}
		ProgressiveBosses-2.1.5-mc1.15.2.jar Progressive Bosses {progressivebosses@2.1.5-mc1.15.2 DONE}
		Morpheus-1.15.2-4.2.50.jar Morpheus {morpheus@version DONE}
		i-am-very-smart-mc1.15.2-forge-2.1.0.jar I Am Very Smart {iamverysmart@2.1.0 DONE}
		LowTechQuarries_1.1.0.jar Low-Tech Quarries {low_tech_quarries@1.1.0 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		SnowRealMagic-1.15.2-1.7.5.jar Snow! Real Magic! {snowrealmagic@1.7.5 DONE}
		leveluphp-mc1.15.2-forge-5.1.2.jar Level Up HP {leveluphp@5.1.2 DONE}
		horsestandstill-1.15.2-1.0.1.jar Stupid Horse Stand Still {horsestandstill@1.15.2-1.0.1 DONE}
		refinedstorage-1.8.5.jar Refined Storage {refinedstorage@1.8.5 DONE}
		PackMenu-1.15.2-1.2.4.jar Pack Menu {packmenu@1.2.4 DONE}
		mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
		dwmh-1.15.2-4.0.0.jar Dude! Where's my Horse? {dwmh@NONE DONE}
		useful_backpacks-1.15.2-1.9.4.63.jar Useful Backpacks {usefulbackpacks@1.9.4.63 DONE}
		torchmaster-2.1.1-rc0.jar Torchmaster {torchmaster@2.1.1-rc0 DONE}
		AmbientSounds_v3.0.20_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		data-loader-mc1.15.2-forge-2.1.0.jar Data Loader {dataloader@2.1.0 DONE}
		AdPoles-1.15.2-4.0.1.0-build.0009.jar To the Bat Poles! {adpoles@4.0.1.0 DONE}
		BiomesOPlenty-1.15.2-10.0.0.365-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.365 DONE}
		Blur-1.1.0-1.jar Blur {blur@1.1.0-1 DONE}
		valhelsia_structures-15.0.3a.jar Valhelsia Structures {valhelsia_structures@15.0.3a DONE}
		Lollipop-1.15.2-1.0.15.jar Lollipop {lollipop@1.0.15 DONE}
		mining_dimension-1.15.2-1.0.4.jar Mining World {mining_dimension@1.15.2-1.0.4 DONE}
		SilentGear-1.15.2-1.8.0+107.jar Silent Gear {silentgear@1.8.0+107 DONE}
		simplefarming-1.15.2-1.2.9_porl.jar Simple Farming {simplefarming@1.15.2-1.2.9 DONE}
		enhanced_anvil-1.15.2-1.0.1.3.jar Enhanced Anvil {enhancedanvil@1.0.1.3 DONE}
		RedstoneExtras-1.15.1-1.0.0.1.jar Easy Redstone Extras {rsx@1.0.0.1 DONE}
		MysticalAdaptations-1.15.2-1.1.jar Mystical Adaptations {mysticaladaptations@NONE DONE}
		MysticalAgradditions-1.15.2-3.0.1.jar Mystical Agradditions {mysticalagradditions@3.0.1 DONE}
		Trapcraft-1.15.2-2.7.0.jar Trapcraft {trapcraft@2.7.0 DONE}
		curios-FORGE-1.15.2-2.0.2.4.jar Curios API {curios@FORGE-1.15.2-2.0.2.4 DONE}
		Patchouli-1.15.2-1.2-34.jar Patchouli {patchouli@1.15.2-1.2-34 DONE}
		collective-1.15.2-1.32.jar Collective {collective@1.32 DONE}
		config-2-3.0.jar Cloth Config v2 API {cloth-config2@3.0 DONE}
		OreExcavation-1.7.151.jar Ore Excavation {oreexcavation@NONE DONE}
		libnonymous-1.15.2-1.1.1.5.jar Libnonymous {libnonymous@1.1.1.5 DONE}
		elevatorid-1.15.2-1.7.1.jar Elevator Mod {elevatorid@1.15.2-1.7.1 DONE}
		Gobber2-1.15.2-2.2.102.jar Gobber 2 {gobber2@2.2.99 DONE}
		obfuscate-0.4.3-1.15.2.jar Obfuscate {obfuscate@0.4.3 DONE}
		wirelessredstone-1.15.2-0.1.0.jar Wireless Redstone {wirelessredstone@0.1.0 DONE}
		antighost-1.15.2-forge31.1.0-1.1.1.jar AntiGhost {antighost@1.15.2-forge31.1.0-1.1.1 DONE}
		NaturesAura-28.2.jar Nature's Aura {naturesaura@28.2 DONE}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		AdChimneys-1.15.2-5.0.5.0-build.0040.jar Advanced Chimneys {adchimneys@5.0.5.0 DONE}
		the_bumblezone-1.15.2-1.3.6.jar The Bumblezone {the_bumblezone@1.15.2-1.3.6 DONE}
		More+Dogs+1.15.2-1.0.6.jar More Dog Breeds {moredogs@1.0.6 DONE}
		FastLeafDecay-v22.jar FastLeafDecay {fastleafdecay@v22 DONE}
		CodeChickenLib-1.15.2-3.3.0.373-universal.jar CodeChicken Lib {codechickenlib@3.3.0.373 DONE}
		attack_speed_enchantment-1.15.2-1.0.2.7.jar Attack Speed Enchantment {attackspeedenchantment@1.0.2.7 DONE}
		unenchanting-1.15.2-2.0.0.jar Unenchanting {unenchanting@1.15.2-2.0.0 DONE}
		rainbowstone-1.15.2-1.1.2.jar Rainbowstone {rainbowstone@1.15.2-1.1.2 DONE}
		doubledoors_1.15-2.1.jar Double Doors {doubledoors@2.1 DONE}
		AdFinders-1.15.2-4.0.5.0-build.0020.jar Advanced Finders {adfinders@4.0.5.0 DONE}
		Cucumber-1.15.2-3.0.8.jar Cucumber Library {cucumber@3.0.8 DONE}
		pamhc2trees-1.15.2-1.0.5.jar Pam's HarvestCraft 2 Fruit Trees {pamhc2trees@version DONE}
		mining-helmet-1.15.2-1.0.8.jar Mining Helmet {mining_helmet@1.0.8 DONE}
		Potion++(1.0.0).jar Potions+ {potionsplus@1.1.0 DONE}
		jei-1.15.2-6.0.2.12.jar Just Enough Items {jei@6.0.2.12 DONE}
		FallingTree-1.15.2-2.1.4.jar Falling Tree {falling_tree@2.1.4 DONE}
		Abnormals-Core-1.15.2-1.0.6.jar Abnormals Core {abnormals_core@1.0.6 DONE}
		Buzzier-Bees-1.15.2-1.5.1.jar Buzzier Bees {buzzierbees@1.5.1 DONE}
		KiwiBirds-1.1.jar Kiwi Birds {kiwibirds@1.1 DONE}
		goblintraders-1.2.0-1.15.2.jar Goblin Traders {goblintraders@1.2.0 DONE}
		Mekanism-1.15.2-9.10.8.421.jar Mekanism {mekanism@9.10.8 DONE}
		skeletonhs_1.15-1.3.jar Skeleton Horse Spawn {skeletonhs@1.3 DONE}
		RingsOfAscension-1.15.2-1.5.jar Rings of Ascension {ringsofascension@1.5 DONE}
		invtweaks-1.15.2-2.0.4.jar Inventory Tweaks Reborn {invtweaks@1.15.2-2.0.4 DONE}
		extraboats-1.3.6-1.15.2.jar Extra Boats {extraboats@1.3.6 DONE}
		Waystones_1.15.2-6.0.1.jar Waystones {waystones@6.0.1 DONE}
		light-overlay-4.7.0.jar Light Overlay Forge {lightoverlay-forge@NONE DONE}
		journeymap-1.15.2-5.7.0b3.jar Journeymap {journeymap@5.7.0b3 DONE}
		comforts-FORGE-1.15.2-2.0.0.3.jar Comforts {comforts@FORGE-1.15.2-2.0.0.3 DONE}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 DONE}
		FruitTrees-1.15.2-1.4.1.jar Fruit Trees {fruittrees@1.4.1 DONE}
		Kiwi-1.15.2-2.7.1.jar Kiwi {kiwi@2.7.1 DONE}
		guicompass_1.15-1.3.jar GUI Compass {guicompass@1.3 DONE}
		BotanyPots-1.15.2-2.0.24.jar BotanyPots {botanypots@2.0.24 DONE}
		VanillaTweaks-1.15.2.1.5.27.jar VanillaTweaks {vanillatweaks@1.15.2.1.5.27 DONE}
		DefaultSettings-1.14.x-1.15.2-2.1.14.jar DefaultSettings {defaultsettings@2.1.14 DONE}
		betteranimalsplus-1.15.2-8.2.1.96.jar Better Animals Plus {betteranimalsplus@8.2.1.96 DONE}
		MagicDoorknob-1.15.2-0.0.6.315.jar Magic Doorknob {magic_doorknob@1.15.2-0.0.6.315 DONE}
		pneumaticcraft-repressurized-1.15.2-1.3.1-39.jar PneumaticCraft: Repressurized {pneumaticcraft@1.15.2-1.3.1-39 DONE}
		The-Endergetic-Expansion-1.15.2-v1.3.1.jar The Endergetic Expansion {endergetic@1.3.1 DONE}
		snowundertrees-1.15.2-v1.1.1.jar Snow Under Trees {snowundertrees@v1.1.1 DONE}
		BonsaiTrees-2.1.2.6.jar Bonsai Trees 2 {bonsaitrees2@2.1.2.6 DONE}
		nhacampfire_1.15-2.3.jar No Hostiles Around Campfire {nhacampfire@2.3 DONE}
		mcjtylib-1.15-4.1.1-beta.jar McJtyLib {mcjtylib@1.15-4.1.1-beta DONE}
		rftoolsbase-1.15-1.1.1-beta.jar RFToolsBase {rftoolsbase@1.15-1.1.1-beta DONE}
		xnet-1.15-2.1.5-beta.jar XNet {xnet@1.15-2.1.5-beta DONE}
		wrench-1.0.0.jar Wrench {wrench@1.0.0 DONE}
		walljump-forge-1.15.2-1.3.5.jar Wall-Jump! {walljump@1.15.2-1.3.5 DONE}
		PackingTape-1.15.2-0.9.6.jar Packing Tape {packingtape@0.9.6 DONE}
		fixedanvilrepaircost_1.15-1.1.jar Fixed Anvil Repair Cost {fixedanvilrepaircost@1.1 DONE}
		EnderStorage-1.15.2-2.5.0.143-universal.jar EnderStorage {enderstorage@2.5.0.143 DONE}
		forge-1.15.2-31.2.22-universal.jar Forge {forge@31.2.22 DONE}
		Waddles-1.15.2-0.8.6.jar Waddles {waddles@1.15.2-0.8.6 DONE}
		Bountiful-1.15.2-3.1.2.jar Bountiful {bountiful@1.15.2-3.1.2 DONE}
		DramaticDoors-1.15.2-1.1.0.jar Dramatic Doors {dramaticdoors@1.15.2-1.1.0 DONE}
		ColossalChests-1.15.2-1.7.9.jar ColossalChests {colossalchests@1.7.9 DONE}
		MysticalAgriculture-1.15.2-3.0.7.jar Mystical Agriculture {mysticalagriculture@3.0.7 DONE}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 DONE}
		CraftingTweaks_1.15.2-11.0.1.jar Crafting Tweaks {craftingtweaks@11.0.1 DONE}
		forge-1.15.2-31.2.22-client.jar Minecraft {minecraft@1.15.2 DONE}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 DONE}
		clockout-1.15.2-1.0.0.jar Clockout {clockout@1.15.2-1.0.0 DONE}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		Psi+r1.2-82.jar Psi {psi@r1.2-80 DONE}
		ImmersiveEngineering-0.15-103.jar Immersive Engineering {immersiveengineering@0.15-101 DONE}
		useful_railroads-1.15.2-1.3.2.DEV_porl.jar Useful Railroads {usefulrailroads@1.3.2.DEV DONE}
		SilentLib-1.15.2-4.6.4+56.jar Silent Lib {silentlib@4.6.4+56 DONE}
		pamhc2crops-1.15.2-1.0.5.jar Pam's HarvestCraft 2 Crops {pamhc2crops@version DONE}
		RingOfGrowth-1.15.2-1.1.33.jar Ring of Growth {ring_of_growth@1.1.31 DONE}
		AdLods-1.15.2-3.0.3.0-build.0035.jar Large Ore Deposits {adlods@3.0.3.0 DONE}
		astikorcarts-1.0.2-1.15.2.jar AstikorCarts {astikorcarts@1.0.2 DONE}
		pamhc2foodcore-1.15.2-1.0.4.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
		gravestone-1.17.5.jar Gravestone Mod {gravestone@1.17.5 DONE}
		cyclepaintings_1.15-1.3.jar Cycle Paintings {cyclepaintings@1.3 DONE}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 DONE}
		Quark-r2.1-245.jar Quark {quark@r2.1-245 DONE}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 DONE}
		FluxNetworks-1.15.2-5.0.1-2.jar Flux Networks {fluxnetworks@1.15.2-5.0.1-2 DONE}
		performant-1.15-2.11m.jar Performant {performant@2.11m DONE}
		themidnight-0.5.9.jar The Midnight {midnight@0.5.9 DONE}
		PickleTweaks-1.15.2-4.0.3.jar Pickle Tweaks {pickletweaks@4.0.3 DONE}
		AppleSkin-mc1.15.2-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
		mobcatcher-2.2.jar Mob Catcher {mobcatcher@2.2 DONE}
		solcarrot-1.15.2-1.9.6.jar Spice of Life: Carrot Edition {solcarrot@1.15.2-1.9.6 DONE}
		Aquaculture-1.15.2-2.0.15.jar Aquaculture 2 {aquaculture@1.15.2-2.0.15 DONE}
		SilentGems-1.15.2-3.5.5+88.jar Silent's Gems 3 {silentgems@3.5.5+88 DONE}
		XL-Food-Mod-1.15.2-2.2.2.jar XL Food Mod {xlfoodmod@2.2.2 DONE}
		CHAS+v1.3+for+1.15.jar Craftable Horse Armour {craftablehorsearmour@1.3 DONE}
		refinedstorageaddons-0.6.2.jar Refined Storage Addons {refinedstorageaddons@0.6.2 DONE}
		SolarGeneration-1.15.2-1.2.2.jar Solar Generation {solargeneration@1.2.2 DONE}
		SoundFilters-0.13_for_1.15.2.jar Sound Filters {soundfilters@0.13_for_1.15.2 DONE}
		horsestats-1.15.1-1.0.1.jar Horse Stats {horsestats@1.0.1 DONE}
		morered-1.15.2-1.0.1.0.jar More Red {morered@1.15.2-1.0.1.0 DONE}
	Kiwi Modules: 
		fruittrees:cherry
		fruittrees:fruittrees
		fruittrees:hybridization
		kiwi:contributors
		kiwi:data
		snowrealmagic:snowrealmagic
	[Psi] Active spell: None
	Patchouli open book context: n/a
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 980 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 451.48, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz

**Versions:**
 - Minecraft Version: 1.15.2
 - Forge Version: 3.2.22
 - Mod Version: 8.2.1.96
 - MultiMC Version: 5 0.6.11-1430
 - Windows 10

**Additional context**
I have been playing a slightly modded version of the "New Beginings" mod pack

**Comment by itsmeow** [comment] 2020-07-17 02:16
Duplicate of #165

**Closed as completed by itsmeow** 2020-07-17 02:16 UTC
